-- CS Knowledge Quiz Questions - Architecture & Incident Response
-- Generated by Gemini CLI
-- Task #4: Architecture + Incident Response 50 Questions

-- ============================================
-- ARCHITECTURE CATEGORY (25 questions)
-- ============================================

-- Difficulty 1 (입문): level_min=1, level_max=25 (6문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'scaling', 1, 1, 25, '새로 런칭한 웹 서비스의 트래픽이 예상보다 빠르게 증가하여 서버 부하가 발생했습니다. 서버의 CPU나 RAM 사양을 높이는 대신, 동일 사양의 서버를 여러 대 추가하여 부하를 분산하는 방식을 무엇이라 하나요?', '이러한 방식을 수평 확장 또는 스케일 아웃(Scale-out)이라고 합니다. 로드 밸런서를 통해 트래픽을 분산하며, 이론적으로 무한한 확장이 가능하다는 장점이 있습니다.', ARRAY['Scale-out', 'Horizontal Scaling', 'Load Balancing'], '서버 한 대의 성능을 올리는 것은 스케일 업(Scale-up)이며 물리적 한계가 있지만, 스케일 아웃은 유연한 확장이 가능합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'caching', 1, 1, 25, '데이터베이스의 읽기 부하를 줄이기 위해 캐시 시스템을 도입하려고 합니다. 애플리케이션이 데이터를 찾을 때 캐시를 먼저 확인하고, 없으면 DB에서 조회한 뒤 캐시에 저장하는 가장 일반적인 전략은?', '이 전략은 Cache Aside(또는 Look-aside) 패턴입니다. 애플리케이션이 직접 캐시와 DB를 조율하며, 캐시 장애 시에도 DB를 통해 서비스가 지속될 수 있는 탄력성을 가집니다.', ARRAY['Cache Aside', 'Look-aside', 'Caching Strategy'], '가장 대중적인 캐시 전략으로 데이터가 필요할 때만 캐시에 로드되는 레이지 로딩 방식입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'microservices', 1, 1, 25, '기존의 거대한 단일 실행 파일 구조인 모놀리식 아키텍처를 기능별로 쪼개어 독립적인 서비스로 배포하는 방식을 무엇이라고 하나요?', '이를 마이크로서비스 아키텍처(MSA)라고 합니다. 각 서비스는 독립적인 데이터베이스를 가질 수 있으며, 언어나 프레임워크를 자유롭게 선택하고 개별적으로 배포할 수 있습니다.', ARRAY['MSA', 'Microservices', 'Monolith'], '서비스 간 독립성을 확보하여 변경의 영향도를 최소화하고 확장성을 높이는 설계 방식입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'api-design', 1, 1, 25, '프론트엔드 팀에서 여러 마이크로서비스의 데이터를 한 번의 호출로 모아서 받고 싶어 합니다. 클라이언트와 서버 사이에 위치하여 요청을 중계하고 데이터 형식을 변환해주는 역할을 무엇이라 하나요?', '이 역할을 API 게이트웨이(API Gateway)가 수행합니다. 인증, 인가, 속도 제한, 요청 라우팅 및 응답 합치기(Aggregation) 기능을 통합하여 관리할 수 있게 해줍니다.', ARRAY['API Gateway', 'Reverse Proxy', 'Routing'], '클라이언트는 내부 구조를 몰라도 게이트웨이 엔드포인트 하나만으로 여러 서비스를 이용할 수 있습니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', '12-factor', 1, 1, 25, '12-Factor App 원칙 중 하나로, 애플리케이션 코드와 설정(Config)을 엄격하게 분리해야 한다고 강조합니다. 데이터베이스 접속 정보나 API 키와 같은 설정값은 주로 어디에 저장하여 관리해야 하나요?', '설정값은 환경 변수(Environment Variables)에 저장하여 관리해야 합니다. 이를 통해 코드 수정 없이 배포 환경(Dev, Stage, Prod)에 따라 다른 설정을 적용할 수 있고 보안성도 높일 수 있습니다.', ARRAY['12-Factor', 'Environment Variables', 'Config'], '설정을 코드에 하드코딩하지 않고 외부에서 주입받는 것이 이 원칙의 핵심입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'traffic-control', 1, 1, 25, '특정 사용자가 짧은 시간 동안 너무 많은 API 요청을 보내 서비스 전체의 가용성을 해치고 있습니다. 이를 방지하기 위해 정해진 시간 동안의 요청 횟수를 제한하는 기법을 무엇이라 하나요?', '이를 속도 제한(Rate Limiting)이라고 합니다. 서버 리소스를 보호하고 공정한 서비스 이용을 보장하기 위해 사용자나 IP별로 요청 가능한 쿼터(Quota)를 설정합니다.', ARRAY['Rate Limiting', 'Throttling', 'Quota'], 'DoS 공격 방어 및 서비스 안정성 확보를 위한 필수적인 아키텍처 요소입니다.', '07-architecture-scalability.md');

-- Difficulty 2 (주니어): level_min=10, level_max=50 (8문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'microservices', 2, 10, 50, '대규모 모놀리스 시스템을 한 번에 MSA로 전환하는 것은 위험합니다. 기존 시스템의 기능을 하나씩 서비스로 추출하여 점진적으로 교체해 나가는 이 패턴의 명칭은 무엇인가요?', '이 패턴은 스트랭글러 피그(Strangler Fig) 패턴입니다. 무화과나무가 기존 나무를 감싸듯, 새 서비스가 기존 기능을 서서히 대체하여 전환 리스크를 최소화합니다.', ARRAY['Strangler Fig', 'Migration', 'Refactoring'], '레거시 시스템을 유지하면서 점진적으로 현대화할 때 가장 권장되는 패턴입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'message-queue', 2, 10, 50, 'Kafka를 사용할 때, 하나의 토픽에 대해 여러 대의 컨슈머가 동시에 데이터를 병렬로 처리하려면 어떤 설정을 일치시켜야 하며, 무엇을 기준으로 데이터가 분산되나요?', '컨슈머 그룹(Consumer Group)을 동일하게 설정해야 하며, 데이터는 파티션(Partition) 단위로 분산됩니다. 동일 그룹 내의 각 컨슈머는 서로 다른 파티션을 할당받아 메시지를 중복 없이 처리합니다.', ARRAY['Kafka', 'Consumer Group', 'Partition'], '파티션 수는 병렬 처리의 단위가 되며, 컨슈머 수가 파티션 수보다 많으면 일부 컨슈머는 대기 상태가 됩니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'resilience', 2, 10, 50, '외부 API 서버의 장애가 우리 서비스로 전파되어 전체 시스템이 마비되는 것을 막고 싶습니다. 장애 발생 시 호출을 즉시 차단하고 미리 정의된 응답(Fallback)을 돌려주는 상태 전이 방식은?', '서킷 브레이커(Circuit Breaker) 패턴입니다. 장애율이 임계치를 넘으면 OPEN 상태가 되어 호출을 차단하고, 일정 시간 후 HALF-OPEN 상태에서 복구 여부를 확인합니다.', ARRAY['Circuit Breaker', 'Fault Tolerance', 'Resilience4j'], '전기 회로 차단기처럼 시스템의 연쇄 장애를 차단하여 가용성을 보존합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'api-design', 2, 10, 50, '모바일 앱과 데스크톱 웹이 필요로 하는 데이터 구조가 서로 달라 API 처리에 어려움이 있습니다. 각 클라이언트 타입에 최적화된 전용 게이트웨이를 별도로 두는 패턴을 무엇이라 하나요?', 'BFF(Backend For Frontend) 패턴입니다. 각 플랫폼(iOS, Android, Web) 요구사항에 맞춘 최적화된 데이터 변환 및 결합 로직을 별도의 계층에서 처리하여 클라이언트 복잡도를 낮춥니다.', ARRAY['BFF', 'Frontend', 'Aggregation'], '클라이언트와 백엔드 간의 강결합을 피하고 플랫폼별 최적화된 경험을 제공합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'cqrs', 2, 10, 50, '주문 시스템에서 데이터 변경(생성, 수정) 로직과 통계/조회 로직이 섞여 성능 최적화가 어렵습니다. 데이터 쓰기 명령과 읽기 조회를 분리하는 아키텍처 패턴은 무엇인가요?', 'CQRS(Command Query Responsibility Segregation) 패턴입니다. 데이터 모델을 읽기 전용과 쓰기 전용으로 분리하여 각 업무에 최적화된 데이터 저장소와 확장 전략을 사용할 수 있게 합니다.', ARRAY['CQRS', 'Read-Write Segregation', 'Performance'], '쓰기와 읽기의 트래픽 비율 차이가 극심한 시스템에서 특히 유용합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'event-driven', 2, 10, 50, 'DB 업데이트와 메시지 큐 발행이 하나의 트랜잭션으로 묶이지 않아 데이터 불일치가 발생할 수 있습니다. 로컬 DB에 발행할 이벤트를 먼저 저장하고, 별도 프로세스가 이를 읽어 큐로 전송하는 패턴은?', '아웃박스(Outbox) 패턴입니다. 데이터 변경과 이벤트 로그 저장을 하나의 로컬 트랜잭션으로 처리하여, 메시지 유실 없이 반드시 한 번은 전달(At-least-once)됨을 보장합니다.', ARRAY['Outbox Pattern', 'Transactional Messaging', 'Eventual Consistency'], '분산 시스템에서 메시지 발행의 신뢰성을 보장하는 핵심 패턴입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'caching', 2, 10, 50, 'DB에 데이터를 쓸 때 캐시에도 동시에 업데이트하여 항상 캐시와 DB의 데이터 일관성을 유지하는 방식을 무엇이라 하나요? (쓰기 지연 없이 즉시 반영)', 'Write-Through 방식입니다. 쓰기 요청 시 캐시와 DB를 모두 업데이트한 후 응답을 반환하므로 데이터 일관성이 높지만, 쓰기 성능은 다소 느려질 수 있습니다.', ARRAY['Write-Through', 'Caching', 'Consistency'], '조회 성능이 매우 중요하고 데이터 손실을 최소화해야 하는 상황에 적합합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'service-mesh', 2, 10, 50, '마이크로서비스 간 통신 시 보안을 강화하고 트래픽 제어를 세밀하게 하고 싶습니다. 애플리케이션 코드 수정 없이 네트워크 통신을 관리하기 위해 사이드카 방식으로 프록시를 배치하는 아키텍처는?', '서비스 메시(Service Mesh)입니다. Istio나 Linkerd 같은 도구를 사용하여 서비스 간 통신(East-West traffic)을 투명하게 관리하고 mTLS를 통한 암호화를 제공합니다.', ARRAY['Service Mesh', 'Sidecar', 'Istio', 'mTLS'], '복잡한 마이크로서비스 환경에서 관찰 가능성과 보안을 담당하는 인프라 계층입니다.', '07-architecture-scalability.md');

-- Difficulty 3 (시니어): level_min=30, level_max=75 (7문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'scaling', 3, 30, 75, '시스템의 일부만 병렬화가 가능할 때, 프로세서를 아무리 늘려도 전체 시스템의 속도 향상은 병렬화되지 않는 부분에 의해 제한된다는 법칙은 무엇인가요?', '암달의 법칙(Amdahl''s law)입니다. 병렬 컴퓨팅에서 성능 향상의 이론적 한계를 설명하며, 순차적으로 실행되어야만 하는 코드의 비율이 전체 성능을 결정함을 시사합니다.', ARRAY['Amdahl''s Law', 'Parallelism', 'Scalability Limit'], '확장성 계획 시 동기화 오버헤드나 순차 처리 구간의 중요성을 강조하는 원칙입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'message-queue', 3, 30, 75, 'Kafka 컨슈머의 처리 속도가 프로듀서의 발행 속도를 따라가지 못해 컨슈머 랙(Consumer Lag)이 심화되고 있습니다. 리소스 증설 외에 아키텍처적으로 대응할 수 있는 가장 효과적인 방법은?', '파티션(Partition) 수를 늘리고 컨슈머 그룹의 인스턴스 개수를 동일하게 늘려 병렬 처리량을 확대해야 합니다. 이때 키를 사용하고 있다면 리파티셔닝(Re-partitioning)에 따른 메시지 순서 보장 문제를 고려해야 합니다.', ARRAY['Consumer Lag', 'Kafka Partition', 'Parallel Processing'], '단순히 컨슈머만 늘리는 것이 아니라 토픽의 파티션 구조 자체가 병렬 처리를 지원해야 합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'distributed-transaction', 3, 30, 75, 'MSA 환경에서 여러 서비스에 걸친 비즈니스 로직의 원자성을 보장하기 위해 2PC(Two-Phase Commit)를 사용했으나 성능 저하가 심각합니다. 각 서비스의 로컬 트랜잭션을 순차적으로 실행하고 실패 시 보상 트랜잭션을 실행하는 패턴은?', '사가(Saga) 패턴입니다. 긴 비즈니스 흐름을 분리된 트랜잭션의 체인으로 관리하며, 실패 시 이전에 성공한 작업을 되돌리는 보상 로직을 실행하여 최종 일관성을 달성합니다.', ARRAY['Saga Pattern', 'Compensating Transaction', 'Eventual Consistency'], '강한 일관성 대신 가용성과 성능을 위해 최종 일관성을 선택하는 대표적인 방법입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'cap', 3, 30, 75, '분산 시스템 설계 중 네트워크 단절(Partition) 상황이 발생했습니다. 데이터의 정확성을 위해 응답을 거부(Consistency 선택)할지, 혹은 오래된 데이터라도 응답(Availability 선택)할지 결정해야 합니다. 이 이론의 명칭은?', 'CAP 정리(Consistency, Availability, Partition Tolerance)입니다. 네트워크 분할이 발생했을 때 일관성과 가용성을 동시에 완벽하게 만족할 수 없으므로, 비즈니스 특성에 맞는 트레이드오프를 선택해야 함을 설명합니다.', ARRAY['CAP Theorem', 'Consistency', 'Availability', 'Partition'], '분산 DB 선택 시(예: Cassandra-AP vs HBase-CP) 핵심적인 판단 기준이 됩니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'ddd', 3, 30, 75, '도메인 주도 설계(DDD)에서 특정 도메인 모델이 적용되는 논리적인 경계를 무엇이라 하며, 서로 다른 두 경계 사이의 모델 변환과 오염 방지를 위해 두는 계층을 무엇이라 하나요?', '경계는 바운디드 컨텍스트(Bounded Context)이며, 모델 오염 방지 계층은 ACL(Anti-corruption Layer)입니다. 이를 통해 각 서비스가 독립적인 비즈니스 언어를 유지하고 타 서비스의 변경에 유연하게 대응합니다.', ARRAY['DDD', 'Bounded Context', 'ACL', 'Ubiquitous Language'], '서비스 분리 기준을 정의하고 마이크로서비스 간의 결합도를 낮추는 핵심 설계 개념입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'serverless', 3, 30, 75, 'AWS Lambda와 같은 서버리스 아키텍처를 도입했으나, 오랜만에 실행될 때 응답 속도가 급격히 느려지는 현상이 발생합니다. 이 현상의 명칭과 이를 완화하기 위한 기술적 전략은 무엇인가요?', '이 현상은 콜드 스타트(Cold Start)라고 합니다. 이를 완화하기 위해 프로비저닝된 가용성(Provisioned Concurrency) 설정을 사용하거나, 주기적인 더미 요청(Warm-up)을 통해 인스턴스를 활성 상태로 유지합니다.', ARRAY['Serverless', 'Cold Start', 'AWS Lambda', 'Warm-up'], '서버리스의 비용 효율성과 지연 시간(Latency) 간의 트레이드오프를 관리하는 것이 중요합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'event-driven', 3, 30, 75, '상태의 최종 결과만 저장하는 대신, 데이터에 발생한 모든 변경 이력을 순차적으로 저장하여 상태를 재구성할 수 있게 하는 패턴은 무엇인가요?', '이벤트 소싱(Event Sourcing) 패턴입니다. 모든 상태 변화를 이벤트 객체로 로그 저장소에 기록하며, 정확한 감사(Audit)가 가능하고 특정 시점의 상태로 복구가 용이하다는 장점이 있습니다.', ARRAY['Event Sourcing', 'Aggregate', 'Audit Log', 'Snapshot'], '주로 CQRS와 결합하여 복잡한 도메인의 상태 관리와 확장성을 동시에 확보할 때 사용합니다.', '07-architecture-scalability.md');

-- Difficulty 4 (리드/CTO): level_min=50, level_max=100 (4문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'conway-law', 4, 50, 100, '대규모 조직에서 마이크로서비스 전환을 추진하고 있으나, 팀 간의 복잡한 의존성 때문에 시스템 설계가 꼬이고 있습니다. "조직의 의사소통 구조가 시스템 설계를 결정한다"는 이 법칙의 명칭과 해결 방향은?', '콘웨이의 법칙(Conway''s Law)입니다. 효율적인 아키텍처를 위해서는 먼저 조직 구조를 원하는 시스템 구조에 맞게 재편(역 콘웨이 전략)하여 팀 간 인터페이스를 명확히 해야 합니다.', ARRAY['Conway''s Law', 'Inverse Conway Maneuver', 'Team Structure'], '기술적인 아키텍처 변화보다 조직 문화와 구조의 변화가 선행되어야 함을 강조합니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'consensus', 4, 50, 100, '분산 시스템에서 여러 노드가 하나의 동일한 결정(예: 리더 선출, 로그 일치)을 내리기 위해 사용하는 알고리즘으로, 이해하기 쉬운 구조를 가져 Kubernetes나 etcd에서 널리 쓰이는 것은?', '래프트(Raft) 합의 알고리즘입니다. 리더 선출, 로그 복제, 안전성을 중심으로 설계를 분리하여 Paxos보다 이해하기 쉬우며, 과반수 이상의 노드가 살아있을 때 시스템의 일관성을 보장합니다.', ARRAY['Raft', 'Paxos', 'Consensus Algorithm', 'etcd'], '분산 시스템의 고가용성과 데이터 일관성을 유지하기 위한 핵심 메커니즘입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'event-driven', 4, 50, 100, '소스 데이터베이스의 변경 사항을 실시간으로 감지하여 외부 시스템으로 스트리밍하는 기술로, Debezium 같은 도구를 활용해 Outbox 패턴 없이도 일관성을 유지하는 방식은?', 'CDC(Change Data Capture)입니다. DB의 바이너리 로그(Binlog)를 직접 읽어 변경 사항을 이벤트로 변환하므로, 애플리케이션 코드 수정 없이도 신속하고 안정적인 데이터 동기화가 가능합니다.', ARRAY['CDC', 'Debezium', 'Binlog', 'Data Streaming'], 'DB 부하를 최소화하면서 이기종 저장소 간의 실시간 실태 동기화를 이룰 수 있는 고성능 전략입니다.', '07-architecture-scalability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('architecture', 'scaling', 4, 50, 100, '글로벌 서비스를 운영하면서 국가별 지연 시간을 최소화하기 위해 중앙 집중형 클라우드 대신 사용자와 가까운 위치에서 로직을 처리하려고 합니다. 이를 지원하는 아키텍처 전략은?', '엣지 컴퓨팅(Edge Computing) 및 엣지 펑션(Edge Functions) 전략입니다. CDN 노드에서 코드를 직접 실행하여 서버 응답 시간을 비약적으로 단축하고 원천 서버(Origin)의 부하를 분산합니다.', ARRAY['Edge Computing', 'Edge Functions', 'Latency', 'Cloudflare Workers'], '네트워크 토폴로지의 끝단에서 데이터를 처리함으로써 초저지연 사용자 경험을 제공하는 현대적 설계 방식입니다.', '07-architecture-scalability.md');


-- ============================================
-- INCIDENT CATEGORY (25 questions)
-- ============================================

-- Difficulty 1 (입문): level_min=1, level_max=25 (6문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'slo', 1, 1, 25, '서비스 가용성을 측정할 때 사용자의 요청 성공률이나 응답 지연 시간을 정의하는 구체적인 지표를 무엇이라고 하나요?', 'SLI(Service Level Indicator)입니다. 이는 서비스 수준을 정량적으로 측정한 결과로, 성공적인 요청의 비율이나 지연 시간의 백분위수 등이 포함됩니다.', ARRAY['SLI', '지표', '가용성', '정량 측정'], 'SLI는 SLO를 설정하기 위한 기초 데이터가 되는 실제 측정값입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'sre', 1, 1, 25, 'SRE 팀에서 반복적이고 수동적이며 자동화가 가능한 가치 없는 작업을 지칭하는 용어는 무엇인가요?', '토일(Toil)입니다. 서비스 운영에 필요하지만 장기적인 가치를 창출하지 못하는 수동적 작업을 의미하며, SRE는 이를 50% 이하로 유지하는 것을 목표로 합니다.', ARRAY['Toil', '토일', '자동화', '운영 부담'], '토일은 자동화를 통해 제거해야 할 대상이며, SRE는 엔지니어링 시간에 집중해야 합니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'incident-response', 1, 1, 25, '운영 중인 서비스의 전체 기능이 마비되어 비즈니스에 치명적인 영향을 주는 장애를 주로 어떤 등급으로 분류하나요?', 'SEV1(Severity 1)입니다. 가장 높은 긴급도를 가지며, 즉각적인 전사적 대응과 Incident Commander 임명이 필요한 수준의 장애를 의미합니다.', ARRAY['SEV1', '장애 등급', '비즈니스 임팩트', '긴급도'], '장애 등급은 영향도와 긴급도를 기준으로 SEV1부터 SEV4까지 분류하는 것이 일반적입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'postmortem', 1, 1, 25, '장애 분석 회의(Postmortem)에서 팀원들이 실수에 대해 처벌받지 않고 솔직하게 논의할 수 있도록 하는 문화를 무엇이라 하나요?', '비난 없는 문화(Blameless Culture)입니다. 개인의 실수를 탓하기보다 시스템적 결함을 찾아 재발을 방지하는 데 집중하는 SRE의 핵심 문화입니다.', ARRAY['Blameless', '비난 없는 포스트모텀', '재발 방지', 'SRE 문화'], '비난이 있으면 문제를 숨기게 되어 더 큰 장애를 초래하므로 시스템 개선에 집중해야 합니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'on-call', 1, 1, 25, '근무 시간 외에도 장애 알람에 즉각 대응하기 위해 지정된 순번의 담당자를 무엇이라 부르나요?', '온콜(On-Call) 담당자입니다. 장애 발생 시 가장 먼저 호출되어 상황을 파악하고 초기 대응을 수행하는 역할을 맡습니다.', ARRAY['On-call', '온콜', '당직', '장애 대응'], '온콜은 서비스 가용성을 보장하기 위한 필수적인 순번제 운영 방식입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'slo', 1, 1, 25, '서비스 가용성 목표가 99.9%일 때, 한 달(30일) 동안 허용되는 최대 가동 중단 시간은 약 얼마인가요?', '약 43분입니다. 99.9%의 가용성은 0.1%의 에러 버짓을 의미하며, 이는 한 달 기준 약 43.2분에 해당합니다.', ARRAY['가용성', '99.9%', '에러 버짓', '가동 중단 시간'], '가용성 목표(99.x%)가 높아질수록 허용되는 중단 시간은 기하급수적으로 줄어듭니다.', '08-incident-sre.md');

-- Difficulty 2 (주니어): level_min=10, level_max=50 (8문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'postmortem', 2, 10, 50, '장애의 근본 원인을 파악하기 위해 문제의 원인에 대해 계속해서 질문을 던지는 기법을 무엇이라 하나요?', '5 Whys 기법입니다. 표면적인 현상에 그치지 않고 ''왜?''라는 질문을 최소 5번 반복하여 문제의 근본적인 시스템 결함을 찾아내는 방식입니다.', ARRAY['5 Whys', '근본 원인 분석', 'RCA', '시스템 개선'], '단순한 인적 실수가 아닌 시스템의 프로세스 부재나 설계 결함을 찾는 것이 목적입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'error-budget', 2, 10, 50, '새로운 기능을 배포할지 아니면 서비스 안정화 작업을 할지 결정하는 기준이 되는 지표는 무엇인가요?', '에러 버짓(Error Budget)입니다. SLO 목표 가용성에서 남은 허용 오차 범위를 의미하며, 버짓을 다 소진하면 안정화될 때까지 신규 배포를 중단합니다.', ARRAY['Error Budget', '에러 버짓', '배포 결정', 'SLO'], '에러 버짓은 개발 속도와 서비스 안정성 사이의 균형을 맞추는 메커니즘입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'incident-response', 2, 10, 50, '장애 대응 현장에서 모든 의사결정 권한을 가지며 대응 팀을 지휘하는 핵심 역할은 무엇인가요?', '인시던트 커맨더(Incident Commander, IC)입니다. 문제 해결에 직접 참여하기보다 전체 상황을 조망하고 자원을 배분하며 커뮤니케이션을 총괄합니다.', ARRAY['IC', 'Incident Commander', '지휘관', '장애 대응 역할'], 'IC는 대응의 효율성을 위해 실무 작업보다는 전체적인 상황 관리와 의사결정에 집중합니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'runbook', 2, 10, 50, '장애 발생 시 담당자가 당황하지 않고 절차에 따라 대응할 수 있도록 미리 작성된 단계별 지침서를 무엇이라 하나요?', '런북(Runbook) 또는 플레이북(Playbook)입니다. 특정 상황에 대한 조치 방법, 연락망, 자동화 스크립트 실행 절차 등을 상세히 기술한 문서입니다.', ARRAY['Runbook', '런북', '대응 지침', '자동화'], '잘 관리된 런북은 MTTR(평균 복구 시간)을 단축하는 데 매우 중요한 역할을 합니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'chaos-engineering', 2, 10, 50, '운영 환경에 인위적인 장애를 주입하여 시스템의 회복 탄력성을 확인하는 활동에서 가장 먼저 정의해야 하는 ''정상 상태''를 무엇이라 하나요?', '스테디 스테이트(Steady State)입니다. 시스템이 정상적으로 동작하고 있을 때의 지표 기준을 정의해야 장애 주입 시의 변화를 정확히 측정할 수 있습니다.', ARRAY['Steady State', '정상 상태', 'Chaos Engineering', '회복 탄력성'], '정상 상태가 정의되지 않으면 장애 주입이 시스템에 미친 영향을 분석할 수 없습니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'release-engineering', 2, 10, 50, '신규 버전을 전체 사용자에게 배포하기 전, 소수의 사용자에게만 먼저 노출하여 문제를 감시하는 배포 전략은?', '카나리(Canary) 배포입니다. 운영 환경의 일부 트래픽만 신규 버전으로 보내 지표를 비교 분석한 후 점진적으로 확대하여 리스크를 최소화합니다.', ARRAY['Canary', '카나리 배포', '점진적 배포', '리스크 관리'], '광부들이 가스 누출을 감지하기 위해 카나리아를 데리고 들어간 것에서 유래한 용어입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'disaster-recovery', 2, 10, 50, '재해 복구 계획에서 장애 발생 시점부터 복구까지 걸리는 최대 허용 시간을 무엇이라 하나요?', 'RTO(Recovery Time Objective, 복구 시간 목표)입니다. 서비스가 중단된 후 비즈니스가 재개되어야 하는 시간적 한계를 의미합니다.', ARRAY['RTO', '복구 시간 목표', 'DR', '서비스 연속성'], 'RTO가 짧을수록 복구 속도는 빠르지만 인프라 구축 비용이 상승하는 트레이드오프가 있습니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'sre', 2, 10, 50, '단순히 서버가 떠 있는지 확인하는 모니터링을 넘어, 내부 상태를 추론하여 복잡한 시스템의 문제를 진단할 수 있는 능력을 무엇이라 하나요?', '관측 가능성(Observability)입니다. 로그, 메트릭, 트레이싱 데이터를 결합하여 시스템 내부에서 무슨 일이 벌어지고 있는지 깊이 있게 이해하는 능력입니다.', ARRAY['Observability', '관측 가능성', '메트릭', '분산 트레이싱'], '관측 가능성은 장애의 ''현상''뿐만 아니라 ''원인''을 파악하는 데 필수적입니다.', '08-incident-sre.md');

-- Difficulty 3 (시니어): level_min=30, level_max=75 (7문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'incident-response', 3, 30, 75, '특정 컴포넌트의 장애가 인접한 시스템으로 전파되어 전체 서비스가 연쇄적으로 무너지는 현상을 무엇이라 하나요?', '카스케이드 실패(Cascading Failure)입니다. 이를 방지하기 위해 서킷 브레이커(Circuit Breaker)나 지수 백오프(Exponential Backoff) 같은 기법을 적용해야 합니다.', ARRAY['Cascading Failure', '카스케이드 실패', '연쇄 장애', '서킷 브레이커'], '한 부분의 부하가 다른 부분으로 넘어가면서 시스템 전체가 과부하되는 현상입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'sre', 3, 30, 75, 'SRE 팀에서 운영 업무(Toil) 비중을 50% 이하로 엄격히 제한하는 가장 핵심적인 이유는 무엇인가요?', '엔지니어링 시간을 확보하여 시스템 자동화와 개선을 수행하기 위해서입니다. 운영에 매몰되면 시스템 개선이 멈추고 기술 부채가 쌓여 결국 더 큰 장애로 이어지기 때문입니다.', ARRAY['50% 규칙', 'SRE 원칙', '자동화 확보', '엔지니어링 시간'], 'SRE는 소프트웨어 공학 기법으로 운영 문제를 해결하는 직군임을 명확히 하는 원칙입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'on-call', 3, 30, 75, '온콜 담당자가 너무 많은 알람에 노출되어 중요한 장애 알람을 무시하게 되는 현상을 방지하기 위한 가장 효과적인 조치는?', 'SLO 기반 알람 설정입니다. 모든 개별 메트릭이 아닌 실제 사용자 경험(SLO)에 영향을 주는 치명적인 상황에서만 호출(Page)이 가도록 필터링하고 나머지는 티켓으로 처리해야 합니다.', ARRAY['Alert Fatigue', '알람 피로도', 'SLO 기반 알람', '우선순위'], '의미 없는 알람을 줄여야 실제 긴급 상황에서 온콜 담당자의 집중력을 유지할 수 있습니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'capacity-planning', 3, 30, 75, '갑작스러운 트래픽 폭증에도 서비스를 안정적으로 유지하기 위해, 평소 필요량보다 더 많은 자원을 미리 확보하는 전략을 무엇이라 하나요?', 'N+2 용량 계획 또는 오버프로비저닝입니다. 주요 인프라 장애나 예측하지 못한 피크 트래픽 발생 시에도 가용성을 유지하기 위한 여유 공간(Headroom)을 확보하는 것입니다.', ARRAY['Capacity Planning', 'N+2', '오버프로비저닝', '수요 예측'], '비용과 안정성 사이에서 비즈니스 요구사항에 맞는 적절한 버스트 용량을 계산해야 합니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'multi-region', 3, 30, 75, '특정 리전 전체가 마비되는 재해 상황에 대비하여, 두 개 이상의 리전에서 동시에 서비스를 운영하며 트래픽을 분산하는 구조는?', 'Active-Active 멀티 리전 구조입니다. 글로벌 로드밸런서를 통해 사용자에게 가장 가까운 리전으로 연결하며, 한 리전 장애 시 즉시 다른 리전으로 전체 트래픽을 넘길 수 있습니다.', ARRAY['Active-Active', '멀티 리전', 'GSLB', '고가용성'], '데이터 동기화와 지연 시간 문제를 해결하는 것이 멀티 리전 설계의 핵심 도전 과제입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'sre', 3, 30, 75, '새로운 서비스가 프로덕션 환경에 배포되기 전, 안정성/모니터링/보안 등의 요건을 충족했는지 검토하는 단계를 무엇이라 하나요?', 'PRR(Production Readiness Review)입니다. SRE와 개발팀이 협력하여 서비스가 운영 환경에서 지속 가능하게 동작할 준비가 되었는지 체크리스트를 기반으로 점검합니다.', ARRAY['PRR', '배포 전 검토', '운영 준비성', '체크리스트'], 'PRR을 통해 운영 단계에서 발생할 수 있는 뻔한 장애 포인트들을 미리 제거할 수 있습니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'chaos-engineering', 3, 30, 75, '운영 환경과 동일한 조건에서 팀원들이 모여 특정 장애 시나리오를 실제로 테스트하고 대응력을 높이는 훈련 세션을 무엇이라 하나요?', '게임 데이(GameDay)입니다. 실제 장애를 주입하거나 시뮬레이션하며 시스템의 약점과 대응 프로세스의 빈틈을 찾아내는 실전 훈련입니다.', ARRAY['GameDay', '게임 데이', '장애 훈련', '대응력 강화'], '도구적인 카오스 엔지니어링보다 사람이 참여하는 게임 데이가 조직의 대응력을 높이는 데 효과적입니다.', '08-incident-sre.md');

-- Difficulty 4 (리드/CTO): level_min=50, level_max=100 (4문제)
INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'error-budget', 4, 50, 100, '이번 분기 에러 버짓을 모두 소진한 상황에서 개발팀이 신규 피처 배포를 강행하려 할 때, SRE 리드는 어떻게 조치해야 하나요?', '에러 버짓 정책(Policy)에 따라 배포를 중단하고 안정성 확보 작업을 우선순위로 강제해야 합니다. 이는 감정적 결정이 아닌 사전에 합의된 SLO 정책에 따른 비즈니스적 의사결정입니다.', ARRAY['Error Budget Policy', '에러 버짓 정책', '배포 중단', '거버넌스'], 'SLO와 에러 버짓은 합의된 계약이므로, 이를 어기는 것은 서비스 신뢰성을 포기하는 것과 같습니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'disaster-recovery', 4, 50, 100, 'RPO(Recovery Point Objective)가 0인 시스템을 구축하기 위해 데이터베이스 계층에서 반드시 구현해야 하는 기술적 요구사항은?', '동기식 복제(Synchronous Replication)입니다. 주 센터에 데이터가 쓰일 때 복제본 센터에도 반드시 쓰여야 완료되도록 하여 데이터 유실 가능성을 완전히 제거해야 합니다.', ARRAY['RPO', '복구 시점 목표', '동기식 복제', '데이터 유실 Zero'], 'RPO 0은 성능 저하(Latency)를 감수하더라도 데이터 정합성을 최우선으로 하는 설계입니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'sre', 4, 50, 100, '조직 내 여러 팀에서 발생하는 토일(Toil)의 총량을 관리하고 줄이기 위한 플랫폼 엔지니어링 관점의 전략은?', '셀프 서비스 플랫폼 제공 및 공통 자동화 도구 표준화입니다. 반복되는 수동 작업을 추상화하여 개발자가 스스로 처리하게 하고, 전사 공통의 운영 도구를 구축해 개별 팀의 운영 부담을 전가합니다.', ARRAY['Platform Engineering', 'Toil Reduction', '셀프 서비스', '자동화 표준화'], '개별 팀의 노력만으로는 토일을 근본적으로 제거하기 어렵기 때문에 플랫폼적 접근이 필요합니다.', '08-incident-sre.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('incident', 'incident-response', 4, 50, 100, '대형 장애 발생 시 경영진이나 고객사 등 외부 이해관계자에게 전달할 상황 브리핑 메시지를 작성할 때 가장 주의해야 할 원칙은?', '추측을 배제하고 확인된 사실(Fact) 기반의 정보와 향후 예상 조치 시간을 투명하게 공유하는 것입니다. 장애의 원인을 성급히 단정 짓기보다 현재 상태와 복구 노력을 명확히 전달하여 신뢰를 유지해야 합니다.', ARRAY['Incident Communication', '장애 공지', '이해관계자 관리', '투명성'], '잘못된 정보 전달은 불필요한 혼란을 야기하므로 Communication Lead의 역할이 매우 중요합니다.', '08-incident-sre.md');
