-- CS Knowledge Quiz Questions - Difficulty 4 (리드/CTO급)
-- Deployment (17) + Monitoring (17) + Security (16) = 50 Questions
-- level_min=50, level_max=100

-- ============================================
-- DEPLOYMENT CATEGORY (17 questions)
-- ============================================

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'multi-region', 4, 50, 100, 'MAU 5000만 글로벌 서비스에서 Active-Active 멀티 리전 Kubernetes 클러스터 배포 전략을 설계해야 합니다. 리전 간 데이터 일관성과 페일오버를 고려한 아키텍처와 배포 순서를 제시하세요.', 'Global Load Balancer(GSLB)로 지리적 라우팅을 구성하고, 각 리전에 독립적인 K8s 클러스터를 운영합니다. 데이터 계층은 CockroachDB나 Spanner 같은 글로벌 분산 DB를 사용하거나, 리전별 DB + CDC 기반 비동기 복제를 적용합니다. 배포 순서는 1) 트래픽 적은 리전부터 카나리 배포, 2) 메트릭 안정화 확인 후 다음 리전 순차 배포, 3) 글로벌 피처 플래그로 기능 활성화를 제어합니다. 페일오버는 헬스체크 기반 자동 DNS 전환과 수동 트래픽 드레인 프로세스를 병행합니다.', ARRAY['Multi-Region', 'Active-Active', 'GSLB', 'Global Database', 'Failover'], '멀티 리전 전략은 CAP 정리의 트레이드오프를 이해하고 비즈니스 요구사항에 맞는 일관성 수준을 선택해야 합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'gitops-governance', 4, 50, 100, '500명 규모 개발 조직에서 GitOps 기반 배포 거버넌스를 구축하려 합니다. 팀별 자율성을 보장하면서도 보안/컴플라이언스를 만족하는 ArgoCD 멀티테넌시 아키텍처를 설계하세요.', 'ArgoCD의 ApplicationProject와 RBAC을 활용하여 팀별 네임스페이스 권한을 분리합니다. 구조: 1) 중앙 플랫폼팀이 클러스터 레벨 리소스(CRD, ClusterRole)와 공통 인프라 관리, 2) 각 팀은 할당된 네임스페이스 내에서 자율 배포, 3) OPA Gatekeeper로 필수 레이블, 리소스 제한, 이미지 레지스트리 화이트리스트 등 정책 강제. Sealed Secrets 또는 External Secrets Operator로 시크릿 관리, 모든 변경은 PR 리뷰 필수로 감사 추적 보장. ApplicationSet의 Generator로 팀별 앱 자동 생성을 템플릿화합니다.', ARRAY['GitOps', 'ArgoCD', 'Multi-tenancy', 'RBAC', 'Governance'], 'GitOps 거버넌스는 기술적 통제와 조직 문화의 균형이 핵심입니다. 과도한 통제는 개발 속도를 저하시킵니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'progressive-delivery', 4, 50, 100, '결제 시스템의 핵심 로직 변경을 배포해야 합니다. 비즈니스 임팩트를 최소화하면서 점진적으로 릴리스하는 전략과 자동 롤백 조건을 설계하세요.', 'Argo Rollouts 또는 Flagger를 활용한 Progressive Delivery를 구성합니다. 단계: 1) 내부 직원 대상 1% 트래픽으로 시작, 2) 결제 성공률/에러율/레이턴시 p99 메트릭을 Prometheus에서 5분 단위로 분석, 3) 자동 승인 조건 충족 시 5% -> 25% -> 100% 점진 확대. 자동 롤백 조건: 결제 실패율 0.1% 초과, p99 레이턴시 500ms 초과, 5xx 에러 발생. 추가로 Feature Flag(LaunchDarkly, Unleash)로 특정 가맹점/결제 수단별 점진 활성화하여 코드 배포와 기능 릴리스를 분리합니다. 모든 트랜잭션은 Shadow Mode로 신구 버전 결과 비교 로깅 후 분석합니다.', ARRAY['Progressive Delivery', 'Argo Rollouts', 'Canary', 'Feature Flag', 'Auto Rollback'], '결제 같은 크리티컬 시스템은 배포와 릴리스를 분리하고, 충분한 관찰 기간을 확보해야 합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'supply-chain-security', 4, 50, 100, 'CI/CD 파이프라인의 공급망 보안(Supply Chain Security)을 강화하려 합니다. SLSA Level 3 이상을 달성하기 위한 파이프라인 아키텍처와 검증 프로세스를 설계하세요.', 'SLSA Level 3 달성을 위한 구성: 1) 빌드 환경 격리 - 에페머럴 빌드 에이전트, 네트워크 격리된 환경에서 빌드, 2) 소스 무결성 - 서명된 커밋만 허용, Branch Protection 필수화, 3) 빌드 무결성 - Sigstore/Cosign으로 이미지 서명, Provenance(빌드 출처 증명) 생성 및 첨부, 4) 의존성 보안 - SBOM(Software Bill of Materials) 자동 생성(Syft), 의존성 스캔(Trivy, Snyk) CI 통합, 5) 배포 시 검증 - Admission Controller(Kyverno/Gatekeeper)에서 서명 검증 필수화, 미서명 이미지 배포 차단. GitHub Actions의 OIDC로 클라우드 인증하여 장기 자격증명 제거합니다.', ARRAY['SLSA', 'Supply Chain Security', 'Sigstore', 'SBOM', 'Provenance'], 'SLSA는 빌드 과정의 무결성을 체계적으로 검증하는 프레임워크로, 공급망 공격 대응의 핵심입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'platform-engineering', 4, 50, 100, '내부 개발자 플랫폼(IDP)을 구축하여 개발팀의 인프라 셀프서비스를 실현하려 합니다. 플랫폼 엔지니어링 관점에서 Golden Path와 추상화 레이어 설계 전략을 제시하세요.', 'IDP 설계 전략: 1) Golden Path 정의 - 표준 기술 스택(언어, 프레임워크, DB)별 템플릿 제공, Backstage 같은 개발자 포털로 서비스 카탈로그화, 2) 추상화 레이어 - Crossplane이나 Terraform으로 인프라를 K8s CRD로 추상화, 개발자는 "Database: postgres-small" 같은 선언만으로 프로비저닝, 3) 셀프서비스 - PR 기반 인프라 요청, 자동 승인 가능한 범위 정의(dev 환경은 자동, prod는 승인 필요), 4) 가드레일 - 비용 한도, 보안 정책을 플랫폼에 내장하여 "안전한 자유" 제공, 5) 피드백 루프 - 플랫폼 사용 메트릭 수집, 개발자 만족도 조사로 지속 개선. Cognitive Load를 낮추는 것이 목표입니다.', ARRAY['Platform Engineering', 'IDP', 'Golden Path', 'Developer Experience', 'Crossplane'], '플랫폼 엔지니어링은 개발자 경험(DX)을 핵심 지표로, "올바른 일을 쉽게" 만드는 데 집중합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'cost-optimization', 4, 50, 100, 'Kubernetes 클러스터의 월 비용이 예산을 초과하고 있습니다. Spot 인스턴스 활용, 리소스 최적화, 비용 거버넌스를 포함한 종합적인 비용 최적화 전략을 수립하세요.', '비용 최적화 전략: 1) Spot 인스턴스 - 상태 없는 워크로드를 Spot 노드 풀로 이전, PodDisruptionBudget 필수 설정, Spot 중단 핸들러로 graceful shutdown, On-Demand와 혼합 구성(7:3), 2) 리소스 최적화 - VPA로 requests/limits 추천값 도출, Goldilocks 대시보드로 리소스 낭비 시각화, 야간/주말 개발 환경 자동 스케일 다운(KEDA + Cron), 3) 거버넌스 - 팀별 ResourceQuota 할당, 비용 태깅 필수화(showback/chargeback), Kubecost로 실시간 비용 모니터링 및 알림, 4) 아키텍처 - 트래픽 적은 서비스는 서버리스(Knative)로 전환하여 0으로 스케일 다운. 비용 절감 목표와 안정성 간 트레이드오프를 경영진과 합의합니다.', ARRAY['Cost Optimization', 'Spot Instance', 'VPA', 'Kubecost', 'FinOps'], '클라우드 비용 최적화는 일회성이 아닌 지속적인 FinOps 문화가 필요합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'zero-downtime-migration', 4, 50, 100, '레거시 온프레미스 시스템을 클라우드 Kubernetes로 무중단 마이그레이션해야 합니다. 데이터 동기화, 트래픽 전환, 롤백 계획을 포함한 마이그레이션 전략을 설계하세요.', '무중단 마이그레이션 전략: 1) Strangler Fig 패턴 - 기능별로 점진적 전환, 신규 기능은 클라우드에서 개발, 2) 데이터 동기화 - CDC(Change Data Capture)로 온프렘 DB -> 클라우드 DB 실시간 복제, 양방향 동기화 기간 확보, 3) 트래픽 전환 - DNS 가중치 기반 점진적 전환(10% -> 50% -> 100%), 헤더 기반 라우팅으로 특정 사용자만 신규 시스템 테스트, 4) 롤백 계획 - DNS TTL 최소화(60초), 동기화 상태 모니터링, 롤백 트리거 조건 명확화(에러율/레이턴시), 5) 검증 - 트래픽 미러링으로 신규 시스템에 복제 트래픽 전송하여 응답 비교. 마이그레이션 윈도우를 정의하고 각 단계별 go/no-go 기준을 수립합니다.', ARRAY['Migration', 'Strangler Fig', 'CDC', 'Zero Downtime', 'Traffic Shifting'], '대규모 마이그레이션은 빅뱅 방식이 아닌 점진적 접근이 리스크를 최소화합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'multi-cluster-strategy', 4, 50, 100, '수십 개의 마이크로서비스가 운영되는 환경에서 멀티 클러스터 Kubernetes 전략을 수립해야 합니다. 단일 대형 클러스터 vs 여러 소형 클러스터의 트레이드오프와 선택 기준을 분석하세요.', '트레이드오프 분석: 단일 대형 클러스터 - 장점: 리소스 효율성(빈 패킹), 서비스 간 통신 단순화, 관리 포인트 축소. 단점: Blast Radius가 큼, etcd 확장성 한계(수천 노드), 팀 간 간섭 가능성. 여러 소형 클러스터 - 장점: 장애 격리, 팀별 독립성, 업그레이드 용이. 단점: 오버헤드(클러스터당 컨트롤 플레인), 서비스 메시 복잡도 증가. 선택 기준: 1) 격리 요구사항(규제, 멀티테넌시), 2) 팀 자율성 수준, 3) 운영 성숙도, 4) 비용. 권장: 환경별(dev/prod) 클러스터 분리 + 도메인/팀별 네임스페이스 격리 조합. Fleet 관리 도구(Rancher, Anthos)로 멀티 클러스터 일관성 유지.', ARRAY['Multi-Cluster', 'Blast Radius', 'Cluster Strategy', 'Federation', 'Fleet Management'], '클러스터 전략은 조직 구조, 규제 요구사항, 운영 역량을 종합적으로 고려해야 합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'deployment-window', 4, 50, 100, '글로벌 이커머스 서비스에서 배포 창(Deploy Window)과 변경 동결 기간(Change Freeze)을 정책적으로 운영하려 합니다. 비즈니스 리스크를 최소화하는 배포 거버넌스 체계를 설계하세요.', '배포 거버넌스 체계: 1) 배포 창 정의 - 트래픽 최저 시간대(새벽 2-5시) 권장, 리전별 시간대 고려하여 순차 배포, 월요일/금요일/공휴일 전날 배포 지양, 2) 변경 동결 - 블랙프라이데이, 연말 대목 2주 전부터 동결, 긴급 보안 패치만 예외(CISO 승인), 3) 위험도 분류 - Low(설정 변경): 자동 배포, Medium(코드 변경): 팀 리드 승인, High(인프라/DB): CAB(Change Advisory Board) 승인, 4) 롤백 준비 - 모든 배포 전 롤백 절차 검증, 롤백 불가 변경(DB 스키마)은 별도 승인 및 확장된 관찰 기간, 5) 메트릭 기반 자동 제어 - 에러율 상승 시 자동 배포 중단. SLO 기반 에러 버짓과 연계하여 버짓 소진 시 배포 자동 차단.', ARRAY['Deploy Window', 'Change Freeze', 'CAB', 'Release Governance', 'Risk Management'], '체계적인 배포 거버넌스는 안정성과 속도의 균형을 조직 차원에서 관리하는 메커니즘입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'db-migration-strategy', 4, 50, 100, '대규모 트래픽 서비스에서 DB 스키마 변경을 무중단으로 수행해야 합니다. Online DDL, Expand and Contract 패턴, 블루그린 DB 전환 중 상황별 최적 전략을 비교 분석하세요.', '전략별 분석: 1) Online DDL - 단순 컬럼 추가/인덱스 생성에 적합, MySQL의 pt-online-schema-change나 gh-ost 사용, 테이블 복사 방식으로 락 최소화, 2) Expand and Contract - 복잡한 변경(컬럼 타입 변경, 분리)에 적합, 단계: 새 컬럼 추가 -> 듀얼 라이트 -> 데이터 마이그레이션 -> 애플리케이션 전환 -> 구 컬럼 삭제, 배포 여러 번 필요하지만 가장 안전, 3) 블루그린 DB - 전체 스키마 대규모 변경 시 고려, 복제본에 스키마 적용 후 프로모션, 데이터 동기화 지연과 롤백 복잡도가 단점. 선택 기준: 변경 복잡도, 다운타임 허용치, 롤백 필요성. 모든 경우 스테이징 환경에서 프로덕션 규모 데이터로 테스트 필수.', ARRAY['Online DDL', 'Expand and Contract', 'Blue-Green DB', 'Zero Downtime', 'Schema Migration'], 'DB 스키마 변경은 가장 위험한 운영 작업 중 하나로, 충분한 테스트와 롤백 계획이 필수입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'ci-cd-optimization', 4, 50, 100, '모노레포 환경에서 CI/CD 파이프라인 실행 시간이 30분 이상 걸려 개발 생산성이 저하되고 있습니다. 빌드 시간을 5분 이내로 단축하기 위한 종합적인 최적화 전략을 제시하세요.', 'CI/CD 최적화 전략: 1) 영향 분석 - Turborepo, Nx, Bazel로 변경된 패키지만 빌드/테스트, 의존성 그래프 기반 선택적 실행, 2) 캐싱 극대화 - 원격 캐시(Turborepo Remote Cache)로 팀 간 캐시 공유, Docker 레이어 캐싱, 의존성 캐싱(node_modules, .m2), 3) 병렬화 - 테스트 샤딩(Jest --shard), 매트릭스 빌드로 환경별 병렬 실행, 독립적인 Job 병렬 처리, 4) 테스트 최적화 - 유닛 테스트와 E2E 분리, 변경 관련 테스트만 필수 실행, 나머지는 비동기, 5) 인프라 - 셀프호스티드 러너로 네트워크 지연 감소, 고성능 인스턴스, 로컬 캐시 스토리지. 병목 분석 도구(BuildPulse 등)로 지속적 모니터링.', ARRAY['CI/CD Optimization', 'Monorepo', 'Build Cache', 'Parallelization', 'Turborepo'], '빌드 시간은 개발자 생산성과 직결되므로 투자 대비 효과가 높은 영역입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'container-runtime', 4, 50, 100, 'Kubernetes 클러스터의 컨테이너 런타임을 Docker에서 containerd로 마이그레이션하려 합니다. 기술적 고려사항과 무중단 전환 절차를 설계하세요.', 'containerd 마이그레이션 전략: 기술적 고려사항: 1) 이미지 호환성 - OCI 표준 이미지는 호환, docker build 워크플로우는 buildkit/kaniko로 전환, 2) Docker 특정 기능 - docker-compose 로컬 개발은 유지 가능, docker exec은 crictl exec으로 대체, 3) 로깅 드라이버 - containerd는 CRI 로깅 사용, 기존 Docker 로깅 설정 재검토. 전환 절차: 1) 신규 노드 풀에 containerd 구성, 2) cordon -> drain으로 기존 노드 비우기, 3) Pod가 새 노드에 스케줄링되어 자연스럽게 전환, 4) 기존 노드 삭제, 5) CI/CD 파이프라인의 docker 명령어를 buildkit/kaniko로 교체. 롤백: 구 노드 풀 유지하여 필요 시 트래픽 복귀.', ARRAY['containerd', 'Container Runtime', 'CRI', 'Docker Migration', 'OCI'], 'Docker에서 containerd로의 전환은 Kubernetes 생태계의 표준화 방향에 맞는 필수 과정입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'iac-governance', 4, 50, 100, '100개 이상의 마이크로서비스 팀이 Terraform으로 인프라를 관리하는 환경에서 IaC 거버넌스를 수립하려 합니다. 모듈 표준화, 정책 시행, State 관리 전략을 설계하세요.', 'IaC 거버넌스 전략: 1) 모듈 표준화 - 중앙 Terraform 모듈 레지스트리 운영, 버전 관리 필수(시맨틱 버저닝), 모듈 문서화 및 예제 코드 제공, 팀은 승인된 모듈만 사용, 2) 정책 시행 - Sentinel/OPA로 Policy as Code, 필수 태깅, 리소스 명명 규칙, 허용된 인스턴스 타입/리전 제한, PR 시점에 정책 검증 자동화, 3) State 관리 - Terraform Cloud/Enterprise 또는 S3+DynamoDB로 원격 State, 팀/환경별 State 분리, State 잠금 필수, 민감 정보는 State에서 제외하고 Vault 연동, 4) 워크플로우 - atlantis나 Terraform Cloud로 PR 기반 plan/apply, 프로덕션은 추가 승인 필요. 드리프트 탐지를 위한 정기 terraform plan 자동화.', ARRAY['IaC Governance', 'Terraform', 'Policy as Code', 'Module Registry', 'State Management'], 'IaC 거버넌스는 인프라 표준화와 팀 자율성의 균형점을 찾는 것이 핵심입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'artifact-management', 4, 50, 100, '컨테이너 이미지와 Helm 차트의 버전 관리 및 환경 간 프로모션 전략을 수립해야 합니다. 불변성 보장, 감사 추적, 비용 최적화를 포함한 아티팩트 관리 체계를 설계하세요.', '아티팩트 관리 체계: 1) 버전 전략 - Git SHA + 시맨틱 버전 조합(v1.2.3-abc1234), latest 태그 지양, 이미지 태그 불변성(동일 태그 덮어쓰기 금지), 2) 프로모션 - dev -> staging -> prod 별도 리포지토리 또는 태그 정책, 재빌드 없이 태그 추가/이동으로 프로모션, 프로모션 기록을 메타데이터로 관리, 3) 감사 추적 - 이미지 서명(Cosign)으로 출처 증명, SBOM 생성 및 저장, 취약점 스캔 결과 첨부, 4) 비용 최적화 - 보존 정책 설정(최근 N개 또는 N일), 태그 없는 이미지 정기 정리, 리전별 미러링으로 다운로드 비용 절감. OCI 레지스트리로 이미지/차트/SBOM 통합 관리. 이미지 크기 최적화(멀티스테이지, distroless)로 저장/전송 비용 절감.', ARRAY['Artifact Management', 'Image Promotion', 'Version Strategy', 'SBOM', 'Registry'], '아티팩트 관리는 배포 파이프라인의 신뢰성과 추적 가능성의 기반입니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'service-mesh', 4, 50, 100, '100개 이상의 마이크로서비스 환경에 Istio 서비스 메시 도입을 검토하고 있습니다. 도입 시 예상되는 복잡성, 성능 오버헤드, 단계적 도입 전략을 분석하세요.', 'Istio 도입 분석: 복잡성 - 학습 곡선(Envoy, VirtualService, DestinationRule), 디버깅 어려움(사이드카 로그 분석), 버전 업그레이드 관리. 성능 오버헤드 - 사이드카당 CPU/메모리 추가(100-200MB), 레이턴시 증가(1-5ms), 대규모에서 컨트롤 플레인 부하. 단계적 도입: 1) 비프로덕션 환경에서 파일럿, 2) mTLS만 먼저 활성화(STRICT 모드 점진적), 3) 관측성(Kiali, Jaeger 통합) 활용, 4) 트래픽 관리(카나리, 서킷 브레이커) 점진 적용, 5) 팀별 네임스페이스 단위로 확대. 대안 검토: Linkerd(경량), Cilium Service Mesh(eBPF 기반, 사이드카 불필요). ROI 분석 후 실제 필요한 기능만 선택적으로 활용하는 것이 중요합니다.', ARRAY['Service Mesh', 'Istio', 'mTLS', 'Sidecar', 'Envoy'], '서비스 메시는 강력하지만 복잡성 비용이 크므로 실제 필요성을 명확히 평가해야 합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'disaster-recovery', 4, 50, 100, 'RPO 5분, RTO 30분을 요구하는 핵심 서비스의 재해 복구(DR) 아키텍처를 설계해야 합니다. 인프라, 데이터, 애플리케이션 계층별 DR 전략과 정기 훈련 계획을 수립하세요.', 'DR 아키텍처: 1) 인프라 계층 - IaC(Terraform)로 DR 리전 인프라 코드화, 평시 최소 리소스 유지(Warm Standby), 자동 스케일 업 스크립트 준비, 2) 데이터 계층 - 5분 RPO 충족을 위해 비동기 복제(RDS Cross-Region, Kafka MirrorMaker), 중요 데이터는 동기 복제 고려, 백업 복구 테스트 정기 수행, 3) 애플리케이션 - GitOps 저장소에서 DR 리전에도 동일 배포, 환경 설정만 분리, DNS 페일오버(Route53 Health Check), 4) 훈련 - 분기별 DR 훈련 실시, 실제 페일오버 수행, MTTR 측정 및 개선, 체크리스트 기반 절차 문서화, 5) 비용 최적화 - 평시 DR 리전 최소 유지, 페일오버 시 자동 확장. 훈련 결과 기반으로 DR 절차 지속 개선.', ARRAY['Disaster Recovery', 'RPO', 'RTO', 'Warm Standby', 'Failover'], 'DR 계획은 문서로만 존재해서는 안 되며, 정기적인 훈련으로 실효성을 검증해야 합니다.', 'docs/04-deployment-cicd.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('deployment', 'kubernetes-upgrade', 4, 50, 100, '프로덕션 Kubernetes 클러스터를 1.28에서 1.30으로 업그레이드해야 합니다. API 호환성 검증, 무중단 업그레이드 절차, 롤백 계획을 포함한 업그레이드 전략을 수립하세요.', 'K8s 업그레이드 전략: 1) 사전 검증 - Deprecated API 사용 여부 확인(kubectl deprecations, Pluto), 워크로드 매니페스트 업데이트, 스테이징 환경에서 전체 업그레이드 리허설, 2) 업그레이드 순서 - 마이너 버전 순차 업그레이드(1.28->1.29->1.30), 컨트롤 플레인 먼저 -> 노드 업그레이드, 관리형 K8s(EKS/GKE)는 컨트롤 플레인 자동 업그레이드 활용, 3) 노드 업그레이드 - 신규 버전 노드 풀 생성, cordon -> drain -> 구 노드 삭제, PodDisruptionBudget으로 가용성 보장, 4) 롤백 - 컨트롤 플레인 롤백은 어려움(etcd 스냅샷 필수), 노드 롤백은 구 노드 풀 복원, 이슈 발생 시 워크로드 버전 롤백으로 대응. 업그레이드 후 모든 워크로드 헬스체크, 모니터링 강화.', ARRAY['Kubernetes Upgrade', 'API Deprecation', 'Control Plane', 'Node Upgrade', 'Rolling Update'], 'K8s 업그레이드는 철저한 사전 검증과 단계적 접근이 필수입니다.', 'docs/04-deployment-cicd.md');

-- ============================================
-- MONITORING CATEGORY (17 questions)
-- ============================================

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'observability-platform', 4, 50, 100, 'MAU 1000만 서비스의 관측 가능성(Observability) 플랫폼을 구축해야 합니다. 메트릭, 로그, 트레이스를 통합하고 비용 효율적인 아키텍처를 설계하세요.', '관측성 플랫폼 아키텍처: 1) 메트릭 - Prometheus + Thanos/Cortex로 장기 저장 및 글로벌 뷰, 중요 메트릭만 저장(카디널리티 관리), Recording Rules로 사전 집계, 2) 로그 - Loki(라벨 기반 인덱싱)로 비용 절감, 또는 Elasticsearch(풀텍스트 검색 필요 시), 로그 레벨 조정(프로덕션 INFO 이상), 샘플링 적용, 3) 트레이스 - Tempo 또는 Jaeger + S3 스토리지, 테일 기반 샘플링(에러/지연만 100% 저장), 4) 통합 - OpenTelemetry로 계측 표준화, Grafana로 통합 대시보드, trace_id로 로그-트레이스 연결, 5) 비용 관리 - 핫/웜/콜드 티어링, 보존 기간 정책, 불필요한 텔레메트리 필터링. 벤더 락인 방지를 위해 OTel 기반 구축 권장.', ARRAY['Observability', 'OpenTelemetry', 'Thanos', 'Loki', 'Grafana'], '대규모 관측성은 비용 폭발을 막기 위해 샘플링과 티어링이 필수입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'slo-program', 4, 50, 100, '조직 전체에 SLO 프로그램을 도입하려 합니다. SLI 선정 기준, SLO 수준 결정 방법, 에러 버짓 정책, 경영진 보고 체계를 포함한 SLO 거버넌스를 설계하세요.', 'SLO 프로그램 설계: 1) SLI 선정 - 사용자 경험 직결 지표(가용성, 레이턴시, 에러율), 서버 측 + RUM(Real User Monitoring) 병행, 서비스별 핵심 SLI 3-5개로 제한, 2) SLO 수준 결정 - 현재 성능 기준선 측정 후 약간 높게 설정, 의존성 SLO보다 낮게(최약 체인), 비즈니스 요구사항/비용과 균형, 3) 에러 버짓 정책 - 버짓 소진 시 기능 배포 중단, 안정성 작업 우선, 정책을 사전에 문서화하고 경영진 합의, 4) 보고 체계 - 주간 SLO 대시보드 리뷰, 월간 경영진 보고(버짓 소비율, 주요 인시던트), 분기별 SLO 조정 검토, 5) 도입 전략 - 핵심 서비스 2-3개로 파일럿, 성공 사례 공유 후 확대. SLO는 계약이므로 준수 문화가 핵심.', ARRAY['SLO', 'SLI', 'Error Budget', 'SRE', 'Governance'], 'SLO 프로그램 성공은 기술보다 조직 문화와 경영진 지원에 달려있습니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'alert-strategy', 4, 50, 100, '온콜 담당자의 알림 피로도(Alert Fatigue)가 심각한 수준입니다. SLO 기반 알림 전략, 다중 윈도우 번 레이트 알림, 에스컬레이션 정책을 포함한 알림 체계를 재설계하세요.', '알림 체계 재설계: 1) SLO 기반 알림 - 개별 메트릭이 아닌 에러 버짓 소진율(Burn Rate)로 알림, 예: "현재 속도로 28일 버짓이 3일 내 소진" 시 Critical, 2) 다중 윈도우 - 단기(5분) + 장기(1시간) 동시 충족 시만 알림, 일시적 스파이크에 반응 방지, 3) 심각도 분류 - P1(Page): 즉시 대응 필요, SLO 위반 임박, P2(Ticket): 업무시간 내 처리, P3(Dashboard): 모니터링만, 4) 에스컬레이션 - 5분 미응답 시 백업 온콜, 15분 후 팀 리드, 심각 시 경영진 통보, 5) 알림 품질 관리 - 월간 알림 리뷰, 거짓 양성 90% 이상이면 조치, 조치 불가능 알림 제거. Alertmanager의 그룹화/억제/라우팅 적극 활용apply.', ARRAY['Alert Fatigue', 'Burn Rate', 'SLO Alerting', 'Escalation', 'On-call'], '좋은 알림은 조치 가능(Actionable)해야 하며, 모든 알림은 정당화되어야 합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'distributed-tracing', 4, 50, 100, '500개 마이크로서비스 환경에서 분산 트레이싱 시스템을 운영하고 있습니다. 트레이스 샘플링 전략, 비용 최적화, 성능 디버깅 워크플로우를 설계하세요.', '대규모 트레이싱 전략: 1) 샘플링 - Head-based 확률적 샘플링(1-5%) + Tail-based 샘플링(에러/지연 100%), OpenTelemetry Collector의 tail_sampling 프로세서 활용, 중요 경로(결제, 인증)는 높은 샘플링률, 2) 비용 최적화 - 스팬 개수 제한(서비스당 max), 불필요한 태그/로그 제거, 보존 기간 단축(7-14일), 스토리지 티어링(S3 Glacier), 3) 디버깅 워크플로우 - 메트릭으로 이상 감지 -> 느린 요청 trace_id 획득 -> 트레이스 타임라인에서 병목 스팬 식별 -> 해당 스팬의 로그 확인 -> 근본 원인 분석, 4) 컨텍스트 전파 - W3C Trace Context 표준화, 모든 서비스 OTel SDK 적용, 메시지 큐/비동기 작업에도 전파 보장. 서비스 맵 자동 생성으로 의존성 시각화.', ARRAY['Distributed Tracing', 'Tail Sampling', 'OpenTelemetry', 'Span', 'Context Propagation'], '트레이싱은 모든 것을 저장할 수 없으므로 전략적 샘플링이 필수입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'prometheus-scale', 4, 50, 100, 'Prometheus가 수백만 시계열을 처리하면서 메모리 부족과 쿼리 지연이 발생하고 있습니다. Thanos 또는 Cortex를 활용한 확장 아키텍처와 마이그레이션 전략을 설계하세요.', 'Prometheus 확장 전략: 아키텍처 비교 - Thanos: 사이드카 방식, 기존 Prometheus에 추가, 객체 스토리지(S3) 활용, 다운샘플링 지원, 도입 용이. Cortex: 완전 분산 아키텍처, 푸시 기반, 멀티테넌시 내장, 대규모 SaaS 적합. 권장 아키텍처(Thanos): 1) Sidecar를 각 Prometheus에 배포, 2) 블록을 S3에 업로드, 3) Thanos Query로 글로벌 뷰 제공, 4) Thanos Compactor로 다운샘플링(5분->1시간->1일), 5) Store Gateway로 장기 데이터 쿼리. 마이그레이션: 1) 기존 Prometheus 유지하며 Sidecar 추가, 2) Thanos Query 배포하여 Grafana 연결, 3) 안정화 후 장기 저장 활성화, 4) Recording Rules로 사전 집계하여 쿼리 부하 감소.', ARRAY['Prometheus', 'Thanos', 'Cortex', 'Time Series', 'Long-term Storage'], 'Prometheus 확장은 단순 스케일 업이 아닌 아키텍처 전환이 필요합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'log-platform', 4, 50, 100, '하루 수십 TB의 로그를 처리해야 합니다. Elasticsearch vs Loki vs ClickHouse 중 요구사항에 맞는 솔루션 선택 기준과 대규모 로그 파이프라인 아키텍처를 설계하세요.', '로그 플랫폼 비교: Elasticsearch - 풀텍스트 검색 최강, APM 통합, 높은 비용(인덱싱), 운영 복잡. Loki - 라벨 기반 인덱싱, 저비용, Grafana 통합, 풀텍스트 검색 약함. ClickHouse - 분석 쿼리 최적화, SQL 지원, 실시간 집계 강점. 선택 기준: 풀텍스트 검색 필수 -> Elasticsearch, 비용 중시 + Grafana 환경 -> Loki, 로그 분석/집계 -> ClickHouse. 대규모 파이프라인: 1) 수집 - OTel Collector 또는 Fluent Bit(경량), 버퍼링 필수, 2) 버퍼 - Kafka로 백프레셔 흡수, 피크 처리, 3) 처리 - 파싱/필터링/샘플링, DEBUG 레벨 제거, 4) 저장 - 핫/웜/콜드 티어링, 압축, 5) 비용 관리 - 보존 정책, 불필요 필드 제거. 민감 정보 마스킹 파이프라인에 통합.', ARRAY['Log Platform', 'Elasticsearch', 'Loki', 'ClickHouse', 'Log Pipeline'], '대규모 로그 시스템은 수집-버퍼-처리-저장 각 단계의 확장성을 고려해야 합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'aiops', 4, 50, 100, '정적 임계값 기반 알림의 한계를 극복하기 위해 ML 기반 이상 탐지를 도입하려 합니다. AIOps 도입 전략, 알고리즘 선택, 거짓 양성 관리 방안을 제시하세요.', 'AIOps 도입 전략: 1) 점진적 접근 - 정적 알림 대체가 아닌 보완으로 시작, 단순 이상 탐지(Z-score, 이동 평균)부터, 성공 후 ML 모델 도입, 2) 알고리즘 선택 - 시계열: Prophet(계절성), ARIMA, STL 분해, 다변량: Isolation Forest, Autoencoder, 실시간: 슬라이딩 윈도우 기반 온라인 알고리즘, 3) 거짓 양성 관리 - 초기 학습 기간(2-4주) 알림 비활성화, 피드백 루프(거짓 양성 마킹 -> 재학습), 이상 탐지는 알림이 아닌 "조사 대상" 제안으로, 심각도 낮게 시작, 4) 운영 - 모델 드리프트 모니터링, 정기 재학습, 설명 가능성(왜 이상인지) 제공 노력, 5) 기대 관리 - 완벽하지 않음을 인정, 인간 판단 보조로 포지셔닝. ROI는 MTTD 개선으로 측정.', ARRAY['AIOps', 'Anomaly Detection', 'Machine Learning', 'False Positive', 'Time Series'], 'AIOps는 만능이 아니며, 정적 알림과 ML의 조합이 현실적인 접근입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'cardinality-management', 4, 50, 100, 'Prometheus 메트릭의 카디널리티가 폭발하여 비용과 성능 문제가 발생했습니다. 카디널리티 관리 전략과 조직 차원의 메트릭 거버넌스를 수립하세요.', '카디널리티 관리 전략: 1) 즉각 대응 - 고카디널리티 메트릭 식별(prometheus tsdb analyze), 문제 레이블 drop(relabel_configs), Recording Rules로 집계 후 원본 제거, 2) 예방 - 레이블 값 제한 정책(user_id 금지, 버킷화된 값 사용), 메트릭 명명 규칙 표준화, PR 리뷰에 메트릭 검토 포함, 3) 거버넌스 - 메트릭 카탈로그 관리(어떤 메트릭이 왜 필요한지), 팀별 카디널리티 쿼터 할당, 정기 메트릭 감사, 4) 아키텍처 - 높은 카디널리티 데이터는 로그/트레이스로 이동, 메트릭은 집계된 지표에 집중, 5) 모니터링 - 카디널리티 추이 대시보드, 급증 시 알림. 개발자 교육으로 "측정 가능하다고 다 메트릭으로 만들지 않기" 문화 정착.', ARRAY['Cardinality', 'Prometheus', 'Metrics Governance', 'Label', 'Time Series'], '카디널리티 관리는 기술과 정책의 조합이며, 사전 예방이 사후 대응보다 효과적입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'dashboard-governance', 4, 50, 100, '수백 개의 Grafana 대시보드가 난립하여 관리가 어렵습니다. 대시보드 표준화, 템플릿 관리, IaC 기반 프로비저닝을 포함한 대시보드 거버넌스를 수립하세요.', '대시보드 거버넌스: 1) 계층 구조 - L1: 서비스 개요(Golden Signals), L2: 서비스 상세(컴포넌트별), L3: 디버깅/조사용, 드릴다운 링크로 연결, 2) 템플릿 표준화 - 서비스 유형별(API, Worker, DB) 기본 템플릿 제공, Grafonnet/Jsonnet으로 코드화, 필수 패널 정의(에러율, 레이턴시, Saturation), 3) IaC 프로비저닝 - Git 저장소에서 대시보드 JSON 관리, Terraform provider 또는 Grafana provisioning으로 배포, PR 리뷰로 품질 관리, 4) 거버넌스 - 폴더 구조 표준(팀/환경별), 명명 규칙 강제, 미사용 대시보드 정기 정리(90일 미접근), 소유자 지정 필수, 5) 변수 표준화 - 공통 변수(environment, service) 일관되게 사용. 플랫폼팀이 템플릿 관리, 서비스팀이 커스터마이징.', ARRAY['Dashboard Governance', 'Grafana', 'Grafonnet', 'Template', 'IaC'], '대시보드도 코드처럼 관리하고, 표준화를 통해 일관된 관측 경험을 제공해야 합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'apm-strategy', 4, 50, 100, '상용 APM(Datadog, New Relic)과 오픈소스 조합(Prometheus+Jaeger+Loki) 중 선택해야 합니다. TCO 분석, 기능 비교, 조직 역량을 고려한 의사결정 프레임워크를 제시하세요.', 'APM 선택 프레임워크: 1) TCO 분석 - 상용: 라이선스 비용(호스트/이벤트 기반), 낮은 운영 비용. 오픈소스: 무료 SW, 높은 운영 인력/인프라 비용, 규모에 따라 역전점 존재, 2) 기능 비교 - 상용: 통합 UI, 즉시 사용 가능, 풍부한 기능, AI 기능. 오픈소스: 커스터마이징 자유, 벤더 락인 없음, 학습 곡선, 3) 조직 역량 - 운영팀 규모/역량, 오픈소스 커뮤니티 참여 의지, 내부 플랫폼팀 존재 여부, 4) 하이브리드 접근 - OpenTelemetry로 계측 표준화하면 백엔드 교체 용이, 초기 상용으로 시작 후 역량 성숙 시 오픈소스 전환, 또는 코어는 오픈소스 + 특정 기능만 상용 보완, 5) 의사결정 - 시간 가치, 코어 역량 집중, 장기 전략 고려. 100명 미만 조직은 상용이 대체로 유리.', ARRAY['APM', 'Datadog', 'Open Source', 'TCO', 'Vendor Lock-in'], 'APM 선택은 단순 비용이 아닌 조직 역량과 전략적 방향을 고려해야 합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'business-metrics', 4, 50, 100, '기술 메트릭(CPU, 에러율)과 비즈니스 메트릭(주문 수, 결제 금액)을 통합하여 관측성 체계를 구축하려 합니다. 비즈니스 영향도 기반 모니터링 전략을 설계하세요.', '비즈니스 메트릭 통합 전략: 1) 비즈니스 SLI 정의 - 주문 성공률, 결제 완료율, 검색 결과 반환율 등 사용자 여정 기반 지표, 분당 주문 수/결제 금액 추이, 2) 기술-비즈니스 연계 - 동일 대시보드에 병렬 표시(에러율 급증 vs 주문 감소 상관관계), 비즈니스 메트릭 이상 -> 기술 원인 드릴다운, 3) 알림 우선순위 - 비즈니스 임팩트 기반 심각도 결정, 분당 매출 영향 추정으로 경영진 커뮤니케이션, 4) 대시보드 구성 - 경영진용: 비즈니스 KPI 중심, 기술 상태 요약, 운영팀용: 기술 메트릭 상세 + 비즈니스 컨텍스트, 5) 수집 방법 - 애플리케이션에서 비즈니스 이벤트 발행, Prometheus Counter로 집계, 또는 별도 분석 파이프라인에서 Prometheus로 Export. 장애 시 "매출 X원 손실" 리포팅으로 투자 정당화.', ARRAY['Business Metrics', 'SLI', 'Impact Analysis', 'Executive Dashboard', 'Revenue'], '비즈니스 메트릭 연계는 관측성의 가치를 경영진에게 증명하는 핵심입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'otel-migration', 4, 50, 100, '여러 벤더 SDK(Datadog, New Relic, 자체 구현)가 혼재된 환경에서 OpenTelemetry로 통합 마이그레이션하려 합니다. 단계별 전환 전략과 리스크 관리 방안을 제시하세요.', 'OTel 마이그레이션 전략: 1) 현황 분석 - 기존 SDK 인벤토리, 서비스별 계측 현황, 의존 기능 파악, 2) 병렬 운영 준비 - OTel Collector 배포, 기존 백엔드로 전송하도록 Exporter 구성(호환 모드), 데이터 비교 검증 환경 구축, 3) 단계적 전환 - Phase 1: 신규 서비스만 OTel SDK, Phase 2: 비핵심 기존 서비스 전환(위험 낮은 순), Phase 3: 핵심 서비스 전환, Phase 4: 기존 SDK 제거, 4) 리스크 관리 - 서비스별 롤백 계획(기존 SDK 복원), 전환 후 데이터 품질 검증(누락, 불일치), 성능 오버헤드 모니터링, 5) 백엔드 유연성 - OTel 전환 후 백엔드 교체 용이(상용 -> 오픈소스), 멀티 백엔드 동시 전송으로 비교 평가. 팀별 교육과 문서화 병행.', ARRAY['OpenTelemetry', 'Migration', 'Vendor SDK', 'Collector', 'Instrumentation'], 'OTel 전환은 장기 프로젝트로 접근하고, 병렬 운영으로 리스크를 관리해야 합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'on-call-optimization', 4, 50, 100, '온콜 담당자의 번아웃이 심각한 상황입니다. 건강한 온콜 문화 구축, 로테이션 최적화, 보상 체계를 포함한 온콜 운영 개선안을 설계하세요.', '온콜 운영 개선안: 1) 알림 품질 - SLO 기반 알림으로 노이즈 감소, 월간 알림 리뷰로 무의미한 알림 제거, 목표: 95% 이상 조치 가능 알림, 2) 로테이션 최적화 - 주간 단위 로테이션(일 단위는 컨텍스트 손실), Follow-the-Sun(글로벌 팀), 팀당 최소 4-5명으로 빈도 적정화, 3) 부담 분산 - Primary/Secondary 백업 체계, 심야 호출 후 다음 날 늦은 출근 허용, 지속적 고부하 서비스는 전담팀 구성, 4) 보상 - 온콜 수당 명확화, 호출 건당 추가 보상, 연속 장애 대응 시 휴식일 부여, 5) 문화 - 비난 없는 포스트모템, 온콜 경험 피드백 루프, 런북 품질 개선 시간 확보, 자동화로 토일 감소. 온콜 메트릭(호출 빈도, MTTR, 업무 외 비율) 트래킹.', ARRAY['On-call', 'Burnout', 'Alert Quality', 'Rotation', 'SRE Culture'], '건강한 온콜 문화는 알림 품질과 조직 지원의 균형에서 나옵니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'multi-region-monitoring', 4, 50, 100, '멀티 리전 서비스의 글로벌 관측성 체계를 구축해야 합니다. 리전별 모니터링, 글로벌 뷰 통합, 크로스 리전 알림 상관관계 분석을 설계하세요.', '글로벌 관측성 설계: 1) 리전별 수집 - 각 리전에 독립적인 모니터링 스택(Prometheus, 로그 수집기), 데이터 주권/지연 시간 고려, external_labels로 리전 식별, 2) 글로벌 뷰 - Thanos Query로 모든 리전 Prometheus 연합 쿼리, 또는 remote_write로 중앙 집중화, 글로벌 대시보드에 리전 셀렉터, 3) 크로스 리전 상관관계 - 트레이스 ID로 리전 간 요청 추적, 글로벌 이벤트(배포, 장애) 타임라인 통합, 리전 간 레이턴시/에러율 비교 대시보드, 4) 알림 - 중앙 Alertmanager로 글로벌 정책 적용, 리전별 로컬 알림 + 글로벌 집계 알림, 한 리전 장애가 다른 리전에 영향 주는지 억제(Inhibition) 규칙, 5) DR - 중앙 모니터링 인프라도 멀티 리전 구성, 한 리전 다운 시에도 글로벌 뷰 유지. 데이터 전송 비용 최적화(집계 후 전송).', ARRAY['Multi-Region', 'Global Monitoring', 'Thanos', 'Federation', 'Cross-Region'], '글로벌 모니터링은 데이터 주권, 비용, 지연 시간의 트레이드오프를 관리해야 합니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'incident-tooling', 4, 50, 100, '인시던트 관리 도구 체인(PagerDuty, Slack, Jira, 상태 페이지)을 통합하여 인시던트 라이프사이클 전체를 자동화하려 합니다. 워크플로우 자동화와 도구 통합 전략을 설계하세요.', '인시던트 도구 통합 전략: 1) 알림 -> 티켓 - Alertmanager -> PagerDuty 연동, 심각도에 따른 에스컬레이션 자동화, 중복 알림 그룹화, 2) 워룸 자동 생성 - PagerDuty 인시던트 생성 시 Slack 채널 자동 생성, 관련자 자동 초대, 인시던트 정보 자동 공유, 3) 타임라인 기록 - Slack 대화 자동 캡처, 주요 액션 타임스탬프 기록, 포스트모템 초안 자동 생성, 4) 상태 페이지 - 인시던트 선언 시 상태 페이지 자동 업데이트, 복구 시 자동 해제, API 연동으로 수동 작업 최소화, 5) 포스트모템 -> 티켓 - 개선 액션 아이템 Jira로 자동 생성, 진행 추적, SLO 영향 자동 계산. 도구: PagerDuty, Incident.io, FireHydrant 등 전문 플랫폼 또는 자체 자동화(Zapier, 스크립트).', ARRAY['Incident Management', 'PagerDuty', 'Automation', 'Status Page', 'War Room'], '인시던트 도구 자동화는 대응 시간을 단축하고 문서화 부담을 줄입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'cost-attribution', 4, 50, 100, '관측성 플랫폼 비용이 급증하고 있습니다. 팀/서비스별 비용 귀속(Chargeback/Showback) 모델과 비용 최적화 인센티브 구조를 설계하세요.', '비용 귀속 전략: 1) 비용 측정 - 서비스/팀별 메트릭 시계열 수, 로그 볼륨, 스팬 수 측정, 레이블/태그로 귀속, Kubecost 또는 자체 대시보드로 시각화, 2) Showback vs Chargeback - Showback: 비용 정보만 공유(인식 제고), Chargeback: 실제 비용 청구(예산 영향), 초기에는 Showback으로 시작 후 Chargeback 전환, 3) 인센티브 구조 - 비용 절감 목표 설정 및 달성 시 보상, 카디널리티/볼륨 감소 캠페인, 효율적인 메트릭/로깅 사례 공유, 4) 정책 - 팀별 쿼터 설정(경고 -> 하드 리밋), 기본 무료 할당량 + 초과분 청구, 플랫폼팀이 최적화 컨설팅 제공, 5) 지속 관리 - 월간 비용 리뷰, 이상 비용 알림, 비용 효율성 리더보드. 비용 의식 문화 정착이 목표.', ARRAY['Cost Attribution', 'Chargeback', 'Showback', 'FinOps', 'Observability Cost'], '관측성 비용 관리는 중앙 통제보다 팀의 자율적 최적화를 유도하는 것이 효과적입니다.', 'docs/05-monitoring-observability.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('monitoring', 'synthetic-monitoring', 4, 50, 100, '글로벌 서비스의 사용자 경험을 사전에 모니터링하기 위해 합성 모니터링(Synthetic Monitoring)을 도입하려 합니다. 전략적 테스트 설계와 RUM과의 통합 방안을 제시하세요.', '합성 모니터링 전략: 1) 테스트 설계 - 핵심 사용자 여정(로그인, 검색, 결제) 스크립트화, 글로벌 여러 위치에서 실행(주요 도시/리전), 실행 주기: API 1분, 브라우저 5분, 2) 테스트 유형 - API 체크: 엔드포인트 가용성/응답시간, 브라우저 체크: 실제 렌더링 성능(Core Web Vitals), Multi-step: 복잡한 트랜잭션 시뮬레이션, 3) 알림 통합 - Synthetic 실패 -> PagerDuty, 사용자 영향 전 사전 탐지, SLO에 Synthetic 지표 포함, 4) RUM 통합 - Synthetic(프로active, 통제된 환경) + RUM(실제 사용자 경험) 상관관계, Synthetic 정상 + RUM 이상 -> 특정 사용자 그룹 문제, 5) 도구 - Datadog Synthetic, Grafana k6, Checkly, 또는 오픈소스(Playwright + 스케줄러). 테스트 유지보수 비용 고려하여 핵심 여정만 선별.', ARRAY['Synthetic Monitoring', 'RUM', 'Core Web Vitals', 'Proactive Monitoring', 'User Journey'], '합성 모니터링은 사용자가 문제를 경험하기 전에 탐지하는 사전적 접근입니다.', 'docs/05-monitoring-observability.md');

-- ============================================
-- SECURITY CATEGORY (16 questions)
-- ============================================

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'zero-trust', 4, 50, 100, '조직에 Zero Trust Architecture를 단계적으로 도입하는 로드맵을 설계하세요. NIST 가이드라인을 기반으로 사용자, 디바이스, 네트워크, 애플리케이션 각 영역의 구현 전략을 제시하세요.', 'Zero Trust 로드맵: 1) 사용자 - 강력한 인증(MFA 필수, Passkey 도입), SSO 통합, 지속적 인증(세션 중 주기적 재검증), 위험 기반 인증(이상 행동 시 추가 인증), 2) 디바이스 - 디바이스 인벤토리 및 상태 관리(MDM/EDR), 디바이스 인증서, 컴플라이언스 체크(패치 상태, 보안 설정), 비준수 디바이스 접근 차단, 3) 네트워크 - 마이크로세그멘테이션, VPN -> ZTNA 전환, 내부 트래픽도 암호화(mTLS), 4) 애플리케이션 - 모든 접근 API 게이트웨이 통과, 애플리케이션별 최소 권한, 세션 기반 접근, 5) 데이터 - 데이터 분류, 민감 데이터 암호화, DLP 통합. 단계: Phase 1(6개월) 인벤토리/MFA, Phase 2(1년) 디바이스/네트워크, Phase 3(2년) 완전 ZT. 점진적 도입으로 비즈니스 영향 최소화.', ARRAY['Zero Trust', 'NIST', 'MFA', 'Microsegmentation', 'ZTNA'], 'Zero Trust는 목적지가 아닌 여정이며, 조직 성숙도에 맞게 단계적으로 도입해야 합니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'identity-governance', 4, 50, 100, '수천 명의 직원과 수백 개의 시스템이 있는 조직에서 IAM(Identity and Access Management) 거버넌스를 수립하려 합니다. RBAC vs ABAC, 특권 접근 관리, 접근 리뷰 프로세스를 설계하세요.', 'IAM 거버넌스 설계: 1) RBAC vs ABAC - RBAC: 역할 기반, 단순 명확, 역할 폭발 가능성. ABAC: 속성 기반(부서+시간+위치), 유연하지만 복잡. 권장: RBAC 기본 + 민감 리소스에 ABAC 보완, 2) 특권 접근 관리(PAM) - 상시 권한 제거(Zero Standing Privileges), Just-In-Time 접근(요청-승인-시간제한), 특권 세션 녹화 및 감사, 비상 접근(Break Glass) 절차 정의, 3) 접근 리뷰 - 분기별 접근 권한 인증(매니저 승인), 퇴사/이동 시 즉시 권한 회수, 미사용 권한 자동 탐지 및 제거, 4) 프로비저닝 - HR 시스템 연동 자동 프로비저닝, 역할 기반 기본 권한 자동 부여, 추가 권한은 요청 워크플로우, 5) 감사 - 모든 접근 로깅, 이상 접근 패턴 탐지, 규정 준수 보고서 자동 생성.', ARRAY['IAM', 'RBAC', 'ABAC', 'PAM', 'Access Review'], '효과적인 IAM은 보안과 생산성의 균형이며, 자동화가 핵심입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'devsecops', 4, 50, 100, '개발 초기부터 보안을 통합하는 DevSecOps 체계를 구축하려 합니다. Shift Left 전략, 자동화된 보안 테스트, 개발자 보안 문화 구축 방안을 설계하세요.', 'DevSecOps 체계 설계: 1) Shift Left - 설계 단계: 위협 모델링(STRIDE), 코딩: IDE 보안 플러그인(Snyk, SonarLint), PR: SAST/시크릿 스캔 자동화, 빌드: 의존성 스캔/SBOM 생성, 배포: DAST/이미지 스캔, 2) 자동화 - CI/CD에 보안 게이트 통합, 심각도별 차단 정책(Critical은 배포 차단), 취약점 자동 티켓 생성, 패치 PR 자동 생성(Dependabot), 3) 도구 체인 - SAST: SonarQube, Semgrep / SCA: Snyk, Trivy / DAST: OWASP ZAP / 시크릿: detect-secrets, Gitleaks / IaC: Checkov, tfsec, 4) 개발자 문화 - 보안 챔피언 프로그램(팀당 1명), 보안 교육(OWASP Top 10, 안전한 코딩), 취약점 수정 시간 SLA, 게임화(보안 점수), 5) 피드백 루프 - 거짓 양성 피드백으로 룰 개선, 보안팀-개발팀 정기 미팅.', ARRAY['DevSecOps', 'Shift Left', 'SAST', 'SCA', 'Security Champion'], 'DevSecOps는 도구만이 아닌 문화 변화이며, 개발자 경험을 해치지 않아야 지속됩니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'secret-management', 4, 50, 100, '대규모 마이크로서비스 환경에서 HashiCorp Vault를 중심으로 한 시크릿 관리 아키텍처를 설계하세요. 동적 시크릿, 자동 교체, Kubernetes 통합을 포함하세요.', 'Vault 중심 시크릿 관리: 1) 아키텍처 - Vault HA 클러스터(3+ 노드), Auto-unseal(Cloud KMS), 네임스페이스로 팀/환경 격리, 모든 접근 감사 로깅, 2) 동적 시크릿 - DB 시크릿 엔진으로 임시 자격증명 발급, TTL 설정(예: 1시간), 사용 후 자동 폐기, 유출 시 영향 최소화, 3) Kubernetes 통합 - Vault Agent Injector: 사이드카로 시크릿 주입, Vault CSI Provider: 볼륨으로 시크릿 마운트, External Secrets Operator: K8s Secret 동기화, 4) 자동 교체 - Vault의 자동 교체 기능 활용, 애플리케이션은 교체에 무중단 대응(재로드), 5) 정책 - 최소 권한 정책(서비스별 경로 제한), 인증 방식: Kubernetes ServiceAccount, OIDC, 개발 환경과 프로덕션 완전 분리. 시크릿 제로(코드에 시크릿 없음) 달성 목표.', ARRAY['Vault', 'Secret Management', 'Dynamic Secrets', 'Kubernetes', 'Auto Rotation'], '동적 시크릿은 정적 비밀번호의 근본적 위험을 제거하는 현대적 접근입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'container-security', 4, 50, 100, 'Kubernetes 환경의 컨테이너 보안 아키텍처를 설계하세요. 이미지 공급망 보안, 런타임 보안, 정책 시행을 포함한 종합적인 보안 체계를 제시하세요.', '컨테이너 보안 아키텍처: 1) 공급망 보안 - 신뢰할 수 있는 베이스 이미지만 허용(화이트리스트), 이미지 스캔(Trivy) CI 필수, 이미지 서명(Cosign) 및 검증, SBOM 생성 및 저장, 2) Admission Control - OPA Gatekeeper/Kyverno로 정책 시행, 미서명 이미지 차단, 취약점 임계치 초과 차단, privileged 컨테이너 금지, 3) 런타임 보안 - Falco로 이상 행동 탐지(쉘 실행, 파일 변경), seccomp/AppArmor 프로파일 적용, Read-only 파일시스템, non-root 실행 강제, 4) 네트워크 - NetworkPolicy로 Pod 간 트래픽 제한, 이그레스 제어, mTLS(서비스 메시), 5) 시크릿 - K8s Secret 대신 Vault 연동, etcd 암호화 활성화. Pod Security Standards Restricted 모드 목표. 지속적 컴플라이언스 모니터링.', ARRAY['Container Security', 'Image Signing', 'Falco', 'OPA', 'Pod Security'], '컨테이너 보안은 빌드-배포-런타임 전 단계에 걸친 다층 방어가 필요합니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'incident-response', 4, 50, 100, '보안 사고 대응(Security Incident Response) 체계를 수립하세요. 탐지-분석-격리-복구-교훈 각 단계별 프로세스와 조직 역할을 정의하세요.', '보안 사고 대응 체계: 1) 탐지 - SIEM(Splunk, Elastic Security)에 보안 로그 집중, 이상 탐지 규칙/ML, 침해 지표(IoC) 모니터링, 외부 신고 채널 운영, 2) 분석 - 사고 심각도 분류(P1-P4), 영향 범위 파악, 타임라인 구성, IoC 추출, 3) 격리 - 감염 시스템 네트워크 격리, 자격 증명 무효화, 악성 프로세스 중단, 증거 보존(포렌식 이미지), 4) 복구 - 클린 시스템 복원, 취약점 패치, 모니터링 강화, 비즈니스 정상화, 5) 교훈 - 포스트모템(비난 없는), 근본 원인 분석, 개선 액션 추적, 유사 공격 방어 강화. 조직: Incident Commander, 기술 리드, 커뮤니케이션 담당, 법무/PR. 정기 모의 훈련(Tabletop Exercise)으로 대응력 검증. 규제 신고 요건(72시간) 준수.', ARRAY['Incident Response', 'SIEM', 'Forensics', 'IoC', 'Post-mortem'], '사고 대응은 사전 준비와 훈련이 핵심이며, 문서화된 프로세스가 필수입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'api-security', 4, 50, 100, '수백 개의 API를 보호하기 위한 API 보안 아키텍처를 설계하세요. 인증/인가, 속도 제한, 입력 검증, API 게이트웨이 보안 정책을 포함하세요.', 'API 보안 아키텍처: 1) 인증/인가 - OAuth 2.0 + OIDC, JWT 검증(서명, 만료, 클레임), 스코프 기반 권한(read/write), mTLS for service-to-service, 2) API 게이트웨이 - 중앙 집중 보안 정책, Rate Limiting(사용자/API별), 요청 크기 제한, 헤더 검증, 3) 입력 검증 - 스키마 검증(OpenAPI), 타입/범위 체크, SQL/XSS 필터링, 허용된 Content-Type만, 4) 공격 방어 - WAF 통합(OWASP CRS), DDoS 방어(CloudFlare), Bot 탐지, 브루트포스 방어(계정 잠금), 5) 모니터링 - API 접근 로깅(민감 데이터 마스킹), 이상 패턴 탐지, 인증 실패 알림, API 남용 탐지. API 인벤토리 관리, 미사용 API 폐기, API 버전 관리. 내부 API도 외부와 동일 수준 보안 적용(Zero Trust).', ARRAY['API Security', 'OAuth', 'Rate Limiting', 'WAF', 'Input Validation'], 'API는 현대 애플리케이션의 주요 공격 표면이므로 체계적인 보안이 필수입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'data-protection', 4, 50, 100, '민감 데이터 보호를 위한 암호화 전략을 설계하세요. 저장 데이터(at-rest), 전송 데이터(in-transit), 사용 중 데이터(in-use) 각각의 암호화 방안과 키 관리 체계를 제시하세요.', '데이터 암호화 전략: 1) At-rest - DB 투명 암호화(TDE), 파일시스템 암호화, 애플리케이션 레벨 필드 암호화(민감 데이터), Envelope Encryption(DEK + KEK), 2) In-transit - TLS 1.3 필수, 내부 통신도 암호화(mTLS), 인증서 자동 관리(cert-manager), Perfect Forward Secrecy 보장, 3) In-use - 메모리 암호화(Intel SGX, AWS Nitro), 동형 암호화(제한적 사용), 민감 데이터 처리 후 즉시 메모리 삭제, 4) 키 관리 - Cloud KMS(AWS KMS, GCP Cloud KMS) 활용, 키 로테이션 자동화(연 1회+), HSM for 마스터 키, 키 접근 감사, 5) 정책 - 데이터 분류(Public/Internal/Confidential/Restricted), 분류별 암호화 요구사항 정의, 개인정보는 최소 수집/보존 기간 제한. Crypto Agility 확보(알고리즘 교체 용이한 설계).', ARRAY['Data Encryption', 'At-rest', 'In-transit', 'KMS', 'Key Management'], '포괄적인 암호화는 데이터 유출 시 영향을 최소화하는 마지막 방어선입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'compliance', 4, 50, 100, 'SOC 2 Type II 인증을 준비하고 있습니다. 보안 통제 구현, 증거 수집 자동화, 지속적 컴플라이언스 모니터링 체계를 설계하세요.', 'SOC 2 준비 체계: 1) 통제 매핑 - TSC(Trust Services Criteria) 기준 현황 갭 분석, 우선순위화(보안 > 가용성 > 기밀성), 각 통제별 책임자 지정, 2) 통제 구현 - 접근 통제: RBAC, 분기별 리뷰, 변경 관리: 승인 워크플로우, 감사 로그, 인시던트 관리: 대응 프로세스, 포스트모템, 암호화: at-rest/in-transit, 백업: 정기 테스트, 3) 증거 자동화 - 설정 스냅샷 자동 수집(AWS Config), 접근 로그 자동 추출, 컴플라이언스 스캔 리포트(Cloud Security Posture), 대시보드로 실시간 상태, 4) 지속적 모니터링 - 드리프트 탐지 및 알림, 분기별 자체 평가, 연간 외부 감사 대비, 5) 문화 - 전 직원 보안 교육, 정책 인지 확인, 예외 관리 프로세스. Drata, Vanta 같은 컴플라이언스 자동화 플랫폼 활용 고려.', ARRAY['SOC 2', 'Compliance', 'Audit', 'Evidence Collection', 'Continuous Monitoring'], 'SOC 2는 일회성 프로젝트가 아닌 지속적인 보안 관리 체계의 증명입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'threat-modeling', 4, 50, 100, '신규 서비스 설계 단계에서 위협 모델링을 수행하려 합니다. STRIDE 프레임워크를 활용한 체계적인 위협 식별 및 완화 전략 수립 프로세스를 설계하세요.', '위협 모델링 프로세스: 1) 범위 정의 - 시스템 경계, 데이터 흐름도(DFD), 신뢰 경계, 자산 식별, 2) STRIDE 분석 - Spoofing(위장): 강력한 인증, 인증서 검증, Tampering(변조): 무결성 검증, 서명, 입력 검증, Repudiation(부인): 감사 로깅, 디지털 서명, Information Disclosure(정보 노출): 암호화, 접근 통제, Denial of Service(서비스 거부): Rate Limiting, 확장성, Elevation of Privilege(권한 상승): 최소 권한, 샌드박싱, 3) 위험 평가 - DREAD 또는 CVSS로 심각도 산정, 비즈니스 영향 고려, 우선순위화, 4) 완화 - 각 위협별 대응책 설계, 수용/완화/전가/회피 결정, 5) 검증 - 설계 리뷰에 보안 포함, 구현 후 보안 테스트, 정기 위협 모델 업데이트. 위협 모델링 도구: Microsoft Threat Modeling Tool, OWASP Threat Dragon.', ARRAY['Threat Modeling', 'STRIDE', 'DREAD', 'Risk Assessment', 'Security by Design'], '위협 모델링은 보안 취약점을 설계 단계에서 발견하는 가장 비용 효과적인 방법입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'cloud-security', 4, 50, 100, '멀티 클라우드 환경(AWS, GCP, Azure)의 보안 아키텍처를 설계하세요. 통합 IAM, 네트워크 보안, 보안 상태 관리(CSPM), 워크로드 보호(CWPP)를 포함하세요.', '멀티 클라우드 보안 아키텍처: 1) 통합 IAM - 중앙 IdP(Okta, Azure AD)로 SSO, 각 클라우드에 OIDC 연동, 역할 매핑 표준화, Cross-account 접근 통제, 2) 네트워크 - 클라우드별 VPC 설계 표준화, 클라우드 간 암호화된 연결(VPN/전용선), 통합 방화벽 정책 관리, 이그레스 제어, 3) CSPM - 멀티 클라우드 CSPM 도구(Prisma Cloud, Wiz), CIS Benchmark 기반 자동 스캔, 드리프트 탐지 및 알림, 컴플라이언스 대시보드, 4) CWPP - 워크로드 보호 에이전트 통합, 취약점 스캔, 런타임 보안, 컨테이너/서버리스 통합 커버리지, 5) 로깅/모니터링 - 클라우드 로그 중앙 집중(SIEM), 통합 보안 대시보드, 크로스 클라우드 상관관계 분석. 보안 정책 코드화(OPA)로 클라우드 간 일관성 확보. 클라우드별 네이티브 보안 서비스 활용과 통합의 균형.', ARRAY['Multi-Cloud', 'CSPM', 'CWPP', 'Cloud Security', 'IAM'], '멀티 클라우드 보안은 복잡성 관리와 일관된 정책 적용이 핵심 과제입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'vulnerability-management', 4, 50, 100, '조직 전체의 취약점 관리 프로그램을 수립하세요. 취약점 발견-평가-우선순위화-수정-검증 프로세스와 SLA 기반 관리 체계를 설계하세요.', '취약점 관리 프로그램: 1) 발견 - 정기 스캔(Nessus, Qualys), CI/CD 통합 스캔(SAST/SCA/DAST), 버그 바운티 프로그램, 위협 인텔리전스 피드, 2) 평가 - CVSS 점수 + 비즈니스 컨텍스트, 익스플로잇 가용성 확인, 자산 중요도 반영, 실제 악용 가능성 분석, 3) 우선순위화 - Risk-based 우선순위(SSVC 고려), Critical + 공개 익스플로잇 = 최우선, 내부 전용 시스템은 상대적 완화, 4) SLA - Critical: 24-72시간, High: 7일, Medium: 30일, Low: 90일, SLA 준수율 KPI화, 5) 수정/검증 - 패치 테스트 -> 스테이징 -> 프로덕션, 수정 후 재스캔 검증, 완화 불가 시 보상 통제(WAF 규칙 등), 6) 리포팅 - 경영진 대시보드, 팀별 취약점 현황, 트렌드 분석. 제로데이 대응 프로세스 별도 정의.', ARRAY['Vulnerability Management', 'CVSS', 'Patch Management', 'SLA', 'Risk-based'], '취약점 관리는 발견만이 아닌 실제 수정까지의 전체 사이클 관리가 핵심입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'security-architecture', 4, 50, 100, 'CISO로서 조직의 보안 프로그램 전체를 설계해야 합니다. 거버넌스, 위험 관리, 기술 통제, 보안 문화를 포함한 종합적인 보안 전략을 제시하세요.', '보안 프로그램 설계: 1) 거버넌스 - 보안 정책/표준/절차 체계, 보안 위원회 운영, 역할 책임 정의(RACI), 규정 준수 프레임워크 선정, 2) 위험 관리 - 자산 인벤토리, 위험 평가 주기화, 위험 수용 기준 정의, 비즈니스 연계 위험 커뮤니케이션, 3) 기술 통제 - 심층 방어(Defense in Depth), 예방/탐지/대응 균형, 자동화 우선, 보안 아키텍처 표준, 4) 인력/문화 - 보안 인식 교육(전사), 보안 챔피언 프로그램, 피싱 시뮬레이션, 비난 없는 보고 문화, 5) 측정/개선 - 보안 KPI/KRI 정의, 정기 평가(펜테스트, 감사), 성숙도 모델(NIST CSF), 벤치마킹, 6) 예산/로드맵 - 위험 기반 투자 우선순위, 단기/중기/장기 로드맵, 경영진 보고 체계. 보안은 비용이 아닌 비즈니스 enabler로 포지셔닝.', ARRAY['Security Program', 'CISO', 'Governance', 'Risk Management', 'Security Culture'], '보안 프로그램 성공은 기술만이 아닌 사람, 프로세스, 문화의 통합에 달려있습니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'supply-chain-attack', 4, 50, 100, '소프트웨어 공급망 공격(Supply Chain Attack)에 대응하기 위한 보안 전략을 설계하세요. 의존성 관리, 빌드 파이프라인 보안, 서드파티 위험 관리를 포함하세요.', '공급망 보안 전략: 1) 의존성 관리 - lock 파일로 버전 고정, 의존성 무결성 검증(체크섬), 내부 미러/프록시 레지스트리, 신규 의존성 승인 프로세스, 최소 의존성 원칙, 2) 빌드 보안 - 격리된 빌드 환경(에페머럴), 빌드 재현성(Reproducible Build), 아티팩트 서명(Sigstore), Provenance 생성, SLSA 레벨 달성, 3) 서드파티 관리 - 벤더 보안 평가(설문, SOC 2), 계약에 보안 요구사항 명시, 정기 재평가, 대안 벤더 확보, 4) 탐지 - 의존성 취약점 실시간 모니터링(Snyk, Dependabot), 알려진 악성 패키지 탐지, 비정상 업데이트 알림, 5) 대응 - 취약 의존성 신속 교체 프로세스, 영향 범위 파악 자동화, 통신 계획. Log4Shell 같은 사례 학습하여 대응 시간 최소화.', ARRAY['Supply Chain Security', 'Dependency Management', 'SLSA', 'Third-party Risk', 'Sigstore'], '공급망 공격은 신뢰 체인을 악용하므로 모든 단계의 검증이 필요합니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'security-monitoring', 4, 50, 100, 'SIEM을 중심으로 한 보안 모니터링 체계를 구축하세요. 로그 수집, 탐지 규칙 개발, 위협 헌팅, SOC 운영 모델을 포함한 종합적인 설계를 제시하세요.', '보안 모니터링 체계: 1) 로그 수집 - 우선순위: 인증/인가, 네트워크 플로우, 엔드포인트, 클라우드 API, 정규화/파싱, 보존 정책(규정 준수), 2) SIEM 설계 - Splunk, Elastic Security, 또는 클라우드 네이티브(Sentinel), 상관관계 엔진, 대시보드/알림 구성, 3) 탐지 - 시그니처 기반(알려진 IoC), 행위 기반(비정상 패턴), MITRE ATT&CK 매핑, 탐지 규칙 버전 관리(Git), 4) 위협 헌팅 - 가설 기반 조사, 정기 헌팅 사이클, 위협 인텔리전스 활용, 새 탐지 규칙으로 전환, 5) SOC 운영 - Tier 1(알림 분류), Tier 2(조사), Tier 3(헌팅/규칙 개발), 24/7 vs 업무시간 결정, 아웃소싱 vs 인하우스, 6) 메트릭 - MTTD, MTTR, 거짓 양성률, 탐지 커버리지. SOAR로 대응 자동화 단계적 도입.', ARRAY['SIEM', 'SOC', 'Threat Hunting', 'MITRE ATT&CK', 'Detection Engineering'], 'SOC는 기술과 프로세스, 숙련된 인력의 조합이며 지속적 개선이 필수입니다.', 'docs/06-security.md');

INSERT INTO questions (category, subcategory, difficulty, level_min, level_max, question_text, correct_answer, keywords, explanation, source_doc) VALUES
('security', 'pq-crypto', 4, 50, 100, '양자 컴퓨팅 시대에 대비한 암호화 전략을 수립하세요. 포스트 퀀텀 암호화(PQC) 도입 로드맵, Crypto Agility 확보, 우선순위화 기준을 제시하세요.', 'PQC 대응 전략: 1) 현황 평가 - 암호화 인벤토리(어디서 무슨 알고리즘), 장기 보관 데이터 식별("수집 후 해독" 위험), 의존성 분석(라이브러리, 서비스), 2) NIST PQC 표준 - Kyber(키 교환), Dilithium(서명) 등 최종 표준 학습, 하이브리드 접근(기존 + PQC 병행)으로 전환, 3) Crypto Agility - 암호 알고리즘 추상화 레이어 구축, 설정으로 알고리즘 교체 가능, 프로토콜 버전 협상 지원, 4) 우선순위 - 장기 기밀 데이터 암호화 우선, 서명보다 키 교환 먼저, 외부 통신 > 내부 통신, 5) 로드맵 - 2024-2025: 인벤토리/교육, 2025-2026: 하이브리드 파일럿, 2027+: 전면 전환, 6) 테스트 - PQC 성능 영향 평가(키 크기 증가), 호환성 테스트. 벤더 PQC 지원 로드맵 확인.', ARRAY['Post-Quantum Cryptography', 'PQC', 'Crypto Agility', 'NIST', 'Kyber'], 'PQC 전환은 수년이 걸리는 장기 프로젝트이므로 지금부터 준비해야 합니다.', 'docs/06-security.md');
