ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS estimated_salary int NOT NULL DEFAULT 2400,
  ADD COLUMN IF NOT EXISTS best_combo int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weekly_exp int NOT NULL DEFAULT 0;
